### ISSUE TITLE
u-upload 微信小程序，无法弹出选择，图片，拍照，点击无反应，目前鸿蒙，小米，测试不行

### ISSUE THREAD

**Issue by pigping88** [umicro/uView2.0#1006]
### 版本
2.0.36

### 转载链接
[https://www.baidu.com/](https://www.baidu.com)

### 重现步骤
<template>
	<u-upload
		:fileList="fileList1"
		@afterRead="afterRead"
		@delete="deletePic"
		name="1"
		multiple
		capture="['album', 'camera']"
		:maxCount="10"
	></u-upload>
</template>

<script>
	export default {
		data() {
			return {
				fileList1: [],
			}
		},
		methods:{
			// 删除图片
			deletePic(event) {
				this[`fileList${event.name}`].splice(event.index, 1)
			},
			// 新增图片
			async afterRead(event) {
				// 当设置 multiple 为 true 时, file 为数组格式，否则为对象格式
				let lists = [].concat(event.file)
				let fileListLen = this[`fileList${event.name}`].length
				lists.map((item) => {
					this[`fileList${event.name}`].push({
						...item,
						status: 'uploading',
						message: '上传中'
					})
				})
				for (let i = 0; i < lists.length; i++) {
					const result = await this.uploadFilePromise(lists[i].url)
					let item = this[`fileList${event.name}`][fileListLen]
					this[`fileList${event.name}`].splice(fileListLen, 1, Object.assign(item, {
						status: 'success',
						message: '',
						url: result
					}))
					fileListLen++
				}
			},
			uploadFilePromise(url) {
				return new Promise((resolve, reject) => {
					let a = uni.uploadFile({
						url: 'http://192.168.2.21:7001/upload', // 仅为示例，非真实的接口地址
						filePath: url,
						name: 'file',
						formData: {
							user: 'test'
						},
						success: (res) => {
							setTimeout(() => {
								resolve(res.data.data)
							}, 1000)
						}
					});
				})
			},
		}

	}
</script>
就用你的简单例子，微信小程序，点击无响应，h5是可以的

### 期望的结果是什么？
微信小程序，是可以的

### 实际的结果是什么？
目前一直都有

**Comment by Han09** [comment]
+1

**Comment by lijingpan** [comment]
是因为隐私授权，授权之后就正常。

**Comment by 1peak-c** [comment]
> 是因为隐私授权，授权之后就正常。

是只用在微信公众平台那里更新一下用户隐私设置就行了嘛？ 还是说需要写一些代码啥的？
![image](https://github.com/umicro/uView2.0/assets/86000456/92cfc9d9-f132-4f60-a41f-560a1ee1ad6f)

**Comment by WXSCODE** [comment]
具体更新什么，我更新了审核也过了，但是还是不行，代码层面需要改什么吗？

**Comment by pigping88** [comment]
<img width="744" alt="image" src="https://github.com/umicro/uView2.0/assets/114716671/52db7b7d-043b-4fcc-9bf7-71c829fb04eb">
我的是改了这里，然后审核通过了，之后本地开发，调试时，点击上传组件，就会弹出隐私访问授权，点击授权，就正常了

**Comment by stone009** [comment]
+1

**Comment by lijingpan** [comment]
> 用户隐私设置就行了嘛？ 还是说需要写一些代码啥的？

上传的地方要加上弹窗，让用户确认同意。就正常

**Comment by qingyiay** [comment]
> > 用户隐私设置就行了嘛？ 还是说需要写一些代码啥的？
> 
> 上传的地方要加上弹窗，让用户确认同意。就正常

之前不是点击直接出现拍照或者从相册选择吗  现在不行了？

**Comment by qingyiay** [comment]
更新下隐私协议就好了 微信官方没有通知 https://developers.weixin.qq.com/community/develop/doc/000a2e1ba688283c3290abcf96b400?_at=1699259362633
https://developers.weixin.qq.com/community/develop/doc/0002ecbdbc0d88e8eb80d679e6c800?highLine=%25E4%25B8%258A%25E4%25BC%25A0%25E5%259B%25BE%25E7%2589%2587%25E6%25B2%25A1%25E6%259C%2589%25E5%258F%258D%25E5%25BA%2594
已贴出问题与解决方法
