### ISSUE TITLE
app.use(uView) 报错 提示Vue.filter is not a function

### ISSUE THREAD

**Issue by 666-arch** [umicro/uView2.0#1014]
### 版本
2.0.36

    "uview-ui": "^2.0.36",
    "vue": "^3.2.45",

### 重现步骤
import { createSSRApp } from "vue";
import App from "./App.vue";
import uView from 'uview-ui'
export function createApp() {
  const app = createSSRApp(App);
  app.use(uView);
  return {
    app,
  };
}

### 期望的结果是什么？
正常使用uview 2.0 

### 实际的结果是什么？
app.use(uView) 报错 提示Vue.filter is not a function

**Comment by wuryan** [comment]
我也遇到了同样的问题

**Comment by xiaokonglongya** [comment]
使用Vue2.x版本

**Comment by xiaokonglongya** [comment]
使用Vue2.x版本
