### ISSUE TITLE
u-tabbar uview2 使用

### ISSUE THREAD

**Issue by freshgeek** [umicro/uView2.0#1015]
### 这个功能解决了什么问题？
u-tabbar uview2 使用 
目前文档中只有样式的显示，但是这个组件基本都是和点击跳转或者显示对应不同导航内容的，推荐更进一步封装，或者给出对应的最佳实践在demo中，

### 你期望的 API 是怎样的？
u-tabbar uview2 使用 
目前文档中只有样式的显示，但是这个组件基本都是和点击跳转或者显示对应不同导航内容的，推荐更进一步封装，或者给出对应的最佳实践在demo中，

**Comment by freshgeek** [comment]
https://www.uviewui.com/components/tabbar.html

**Comment by xiaokonglongya** [comment]
组件提供的是快捷的能力，而非更多的demo展示，如果你有好的案例，欢迎到我们的官网DOC中，期待你的PR，关于组件内容的这个问题我先关闭了哈。
