### ISSUE TITLE
u-datetime-picker  props不生效

### ISSUE THREAD

**Issue by mikexia930** [umicro/uView2.0#102]
### 版本
2.0.7

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/datetimePicker.html)

### 重现步骤
<u-datetime-picker
        :show="datetimeDrawer.visible"
        :value="datetimeDrawer.value"
        :closeOnClickOverlay="true"
        confirmColor="#F96656"
        confirmText="$t('work.confirm').toString()"
        :cancelText="$t('work.cancel').toString()"
        @confirm="handleDatetimeConfirm"
        @cancel="handleDatetimeCancel"
        @close="handleDatetimeClose"
        mode="datetime"
      ></u-datetime-picker>

### 期望的结果是什么？
 confirmText  cancelText  cancelColor confirmColor 设置生效

### 实际的结果是什么？
 confirmText  cancelText  cancelColor confirmColor 设置了也不生效

**Comment by BeiQiaoT** [comment]
已修复
