### ISSUE TITLE
u-tabs支持长按回调

### ISSUE THREAD

**Issue by 2424004764** [umicro/uView2.0#1021]
### 这个功能解决了什么问题？
比如我的tabs是用户自己创建的，用户可以删除、编辑tabs，我想通过长按的方式触发编辑操作

### 你期望的 API 是怎样的？
在u-tabs组件增加长按的回调事件，并且回调的参数包含当前长按的index

**Comment by 2424004764** [comment]
改源码实现了：
![image](https://github.com/umicro/uView2.0/assets/24261680/0b044e93-b644-4d83-8153-9a65a4c215ab)

接收端：
![image](https://github.com/umicro/uView2.0/assets/24261680/a74a36f0-708f-4fa6-805e-c097412ca288)

**Comment by xiaokonglongya** [comment]
关注后续版本将会添加。
