### ISSUE TITLE
tabbar - 可以动态切换菜单的数量以及配置

### ISSUE THREAD

**Issue by Banlangenn** [umicro/uView2.0#1025]
### 这个功能解决了什么问题？
自定义tabbr 的地址要在小程序tabBar中提前配置

那么如何实现可以动态切换菜单的数量以及配置呢？？
### 你期望的 API 是怎样的？
如图

**Comment by xiaokonglongya** [comment]
动态修改tabbar-item节点数量就可以了哈

**Comment by Banlangenn** [comment]
# 自定义tabbr 的地址要在小程序tabBar中提前配置

怎么在微信小程序中动态修改呢

比如说
我a身份 是 abcd tabbaritem
b 身份 是。efgh tabbaritem

如果相同switchtab跳转。要提前在app。json 配制


动态修改tabbar-item节点数量就可以了哈 -- ui变了 ，但是微信中的配置怎么变呢，

求大佬给的地址

**Comment by xiaokonglongya** [comment]
建议参考微信官方方法实现[地址](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html)

**Comment by Banlangenn** [comment]
文档中提到-在 app.json 中的 tabBar 项指定 custom 字段，同时其余 tabBar 相关配置也补充完整。
<img width="867" alt="image" src="https://github.com/umicro/uView2.0/assets/19684540/8c8c3cd2-3138-4651-b5fb-9878d3362a8a">

-----
就是说 -customUI 的他被tabbar-item节点。想要通过switchtab跳转（也就是新开webview页面）。要在 app.json补充tabBar配置

那么我动态切换了UI 
 如何动态修改 - app.json中的 tabBar配置呢
