### ISSUE TITLE
有关于 u-picker 滑动无法选中问题

### ISSUE THREAD

**Issue by 850817673** [umicro/uView2.0#1026]
### 版本
2.0.36

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/picker.html)

### 重现步骤
官网多级联动中选中第一行第二列，而后选中第二行，第二列数据出现问题。在个人项目中也有当前问题

### 期望的结果是什么？
选中第二行第一列

### 实际的结果是什么？
在行选中时，后面的列没有做清空操作

---
		// 选择器某一列的数据发生变化时触发
		changeHandler(e) {
			const {
				value
			} = e.detail
			let index = 0,
				columnIndex = 0
			// 通过对比前后两次的列索引，得出当前变化的是哪一列
			for (let i = 0; i < value.length; i++) {
				let item = value[i]
				if (item !== (this.lastIndex[i] || 0)) { // 把undefined转为合法假值0
					// 设置columnIndex为当前变化列的索引
					columnIndex = i
					// index则为变化列中的变化项的索引
					index = item

                                        //！！！！！需要新增的清空操作
					for (let j = 0; j < value.length; j++) {
						if (j > i) {
							value[j] = 0
						}
					}

					break // 终止循环，即使少一次循环，也是性能的提升
				}
			}
            ........
          }

**Comment by xiaokonglongya** [comment]
并未复现该问题，麻烦再交流群反馈一下

**Comment by 850817673** [comment]
https://www.uviewui.com/components/picker.html


picker&nbsp;选择器


右侧示例---多列联动


点开（此时默认选择的是&nbsp; &nbsp;中国&nbsp;深圳），你选择厦门。
之后在选择美国，选完之后再选第二列，这时候就有问题







君言卿诺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umicro/uView2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月10日(星期三) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umicro/uView2.0] 有关于 u-picker 滑动无法选中问题 (Issue #1026)





 
并未复现该问题，麻烦再交流群反馈一下

**Comment by xiaokonglongya** [comment]
[#1011 ](https://github.com/umicro/uView2.0/issues/1011) 是否和该问题一致？

**Comment by 850817673** [comment]
是的，麻烦了
&nbsp;


君言卿诺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月11日(星期四) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umicro/uView2.0] 有关于 u-picker 滑动无法选中问题 (Issue #1026)





 
#1011  是否和该问题一致？

**Comment by xiaokonglongya** [comment]
尝试一下在`u-picker.vue` 的`setColumnValues`方法中 添加`this.setLastIndex(this.innerIndex.slice(0,columnIndex))`，放在`this.innerColumns.splice(columnIndex, 1, values)`之后尝试一下

**Comment by xiaokonglongya** [comment]
相似问题已关闭：[#1011 ](https://github.com/umicro/uView2.0/issues/1011)
