### ISSUE TITLE
建议在NavBar中左边返回按钮中添加默认事件

### ISSUE THREAD

**Issue by HimiHL** [umicro/uView2.0#106]
### 这个功能解决了什么问题？
如果不定义leftClick事件时，证明我们不想去掉他的默认行为，如果按照现在的设计来，那么我们需要在每一个使用navbar的页面上都加一个返回的事件处理，这是冗余复杂的操作

### 你期望的 API 是怎样的？
左边返回按钮，在不指定leftClick事件时，添加默认返回上一页的处理。

**Comment by orangepro11** [comment]
2.0.19版本后已添加
