### ISSUE TITLE
popup组件的渐入动画丢失

### ISSUE THREAD

**Issue by snakelzero** [umicro/uView2.0#110]
### 版本
2.0.9

### 转载链接
[www.uviewui.com](https://www.uviewui.com/guide/demo.html)

### 重现步骤
1、通过vue-cli创建uni-app项目，选择默认模板。
2、使用npm方式安装uview-ui。
3、按照npm安装方式对项目进行配置。
4、将项目编译成微信小程序，并在页面中添加popup组件。
5、来回切换popup组件的显示和隐藏。

### 期望的结果是什么？
popup组件能够正常展示渐入动画

### 实际的结果是什么？
在H5端，动画效果正常。微信小程序端会随机丢失渐入动画，而且不止popup组件，modal组件也会出现这种情况，有可能别的带有渐入动画的组件也会出现。

---
1、组件样式全部使用默认设置，没有使用自定义样式。
2、官网的演示小程序中popup组件并没有出现动画丢失的情况，不知道是版本问题还是什么原因。

**Comment by orangepro11** [comment]
已确认是transition的渐变闪烁问题
