### ISSUE TITLE
2.0的SwipeAction 初始化的时候出现bug

### ISSUE THREAD

**Issue by LiaoShuaiAcount** [umicro/uView2.0#111]
### 版本
2.0.9

### 转载链接
[localhost/](http://localhost:8080/#/pages/index/index)

### 重现步骤
`<template>
	<view>
		<u-swipe-action>
			<u-swipe-action-item
			  :options="options1"
			  :show="false"
			>
				<view>
					<view class="view-fixed u-border-top u-border-bottom" style="width: 100%; ">
						<u--image :showLoading="true" :src="src" width="180rpx" height="180rpx" mode="aspectFit" @click="click"></u--image>
						<text>基础使用</text>
					</view>
				</view>
			</u-swipe-action-item>
			<u-swipe-action-item
			  :options="options1"
			>
				<view>
					<view class="view-fixed u-border-top u-border-bottom" style="width: 100%; ">
						<u--image :showLoading="true" :src="src" width="220rpx" height="180rpx" mode="aspectFit" @click="click"></u--image>
						<text class="text-fixed">基础使用基础使用基础使用基础使用基础使用基础使用基础使用基础使用基础使用基础使用基础使用基础使用基础使用</text>
					</view>
				</view>
			</u-swipe-action-item>
		  </u-swipe-action>
	</view>
</template>`

### 期望的结果是什么？
默认不显示右滑的按钮，
然后图片和文字内容最好可以设置宽度限制比例。
同时文字超过以后省略号表示

### 实际的结果是什么？
默认直接显示了 右滑才会出现的按钮。并且挡住了我的文字。
在滑动操作后，显示正常。

---
就这段代码 不管是浏览器 还是 移动端 都是这样的问题。

**Comment by zzx18023** [comment]
```css
/* App.vue */
.u-swipe-action-item__content {
  position: relative;
}
```
