### ISSUE TITLE
u--input  readonly无效

### ISSUE THREAD

**Issue by KiteWorld** [umicro/uView2.0#112]
### 版本
2.0.9

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/input.html)

### 重现步骤
u--input  是 input 封装成的，readonly  uni-app官网上是没有的，应该是不支持。uview 的文档上应该说明一下nvue 不支持。搞得开发者一脸懵逼

### 期望的结果是什么？
readonly无效

### 实际的结果是什么？
readonly有效

---
uview 的文档上应该说明一下nvue 不支持

**Comment by 79229788** [comment]
不止nvue 不支持，vue也不支持，全平台不支持，应该是开发时漏了这个功能

**Comment by white-007** [comment]
对，vue也不支持u-input的readonly，搞的我一脸懵逼

**Comment by KiteWorld** [comment]
2.0.11版本 readonly 还是无效。发布日志说修复了。

**Comment by yatoku** [comment]
已修复
