### ISSUE TITLE
u-cell  的 rightIcon 属性只有在 isLink 为 true 的时候才生效。

### ISSUE THREAD

**Issue by KiteWorld** [umicro/uView2.0#116]
### 版本
2.0.9

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/cell.html)

### 重现步骤
u-cell  rightIcon属性只有在 isLink 为 true 的时候才生效。不清楚组件本身是不是这样设计的。如果是，建议在文档上说明一下。不看源码真的一脸懵逼

### 期望的结果是什么？
rightIcon 直接生效，不需要 isLink 为 true

### 实际的结果是什么？
rightIcon 属性只有在 isLink 为 true 的时候才生效

**Comment by KiteWorld** [comment]
同时建议给右边图标加上点击事件

**Comment by orangepro11** [comment]
这种情况建议使用插槽解决
