### ISSUE TITLE
transition bug

### ISSUE THREAD

**Issue by 13714273163** [umicro/uView2.0#118]
### 版本
2.0.3

### 重现步骤
<button @click="show = !show">btn</button>
<u-transition mode="fade" :show="show" duration="2000" @afterEnter="afterEnter">
			test transition
</u-transition>

### 期望的结果是什么？
应该2s后才执行afterEnter吧

### 实际的结果是什么？
立刻执行

---
看了下是transition.js里面的vueEnter方法，直接在this.$nextTick()里面emit（‘afterEnter’）了，这样不妥当吧，改成setTimeout(this.onTransitionEnd, this.duration)？貌似也不合适，可能会有误差，应该要监听动画end的实际emit。

**Comment by meng-ling-feng** [comment]
duration="2000" 是动画持续时间，如果有延迟的需要，可以自己加定时器。

**Comment by orangepro11** [comment]
将在2.0.23版本修复
