### ISSUE TITLE
uview tabbar 出现白边

### ISSUE THREAD

**Issue by tpa-wy** [umicro/uView2.0#121]
### 版本
2.0.3 

### 转载链接
[localhost/pages/index/index](https://localhost:5000/pages/index/index)

### 重现步骤
在安卓端和ios端都发现了此问题

### 期望的结果是什么？
取出tabbar的底部白边

### 实际的结果是什么？
使用自定义tabbar出现了白边
并没有在更新日志中发现修复tabbar白边的问题 app端 h5中没有出现此问题

**Comment by tpa-wy** [comment]
111

**Comment by yatoku** [comment]
建议不要发这种链接 看不见实际效果...

**Comment by tpa-wy** [comment]
很抱歉现在才回复
图片链接
http://wig.tpa-wy.xyz/uview.pic.jpg

**Comment by tpa-wy** [comment]
pages代码
"tabBar": {
		"list": [{
				"pagePath": "pages/live/live"
			}, {
				"pagePath": "pages/follow/follow"
			},
			{
				"pagePath": "pages/my/my"
			}, {
				"pagePath": "pages/my/merchant"
			}
		]
	},
用法是在四个tabbar页面中按照文档开发的
