### ISSUE TITLE
2.0 的SwipeActionItem 的  show 属性没效果

### ISSUE THREAD

**Issue by LiaoShuaiAcount** [umicro/uView2.0#129]
不知道为啥默认就是全部打开了，然后设置 :show="false" 完全没有达到控制效果。

![image](https://user-images.githubusercontent.com/49898458/144573698-370823ad-d8be-473f-bfaf-4f59f4a72564.png)

**Comment by LiaoShuaiAcount** [comment]
解决办法
/* App.vue */
.u-swipe-action-item__content {
  position: relative;
}

**Comment by hui-gith** [comment]
// app.vue 加上这个
.u-swipe-action-item__content {
      position: relative;
}

**Comment by hanyucd** [comment]
这个问题，我也遇到了。我加上这个：

.u-swipe-action-item__content {
   position: relative;
}
也没效果呀，还是报错。

@BeiQiaoT 官方能解决下嘛

**Comment by YourException** [comment]
同样的问题：show属性没有作用。
需求：提供一个可以手动关闭滑块的方法。

按照上述方法，在APP.vue中添加如下样式，依然没有效果。
.u-swipe-action-item__content {
position: relative;
}
希望官方能解决此bug。

**Comment by cjlhll** [comment]
没有效果。24年7月了。还是没修复吗
