### ISSUE TITLE
自定义全局的span样式跟uview的图标冲突

### ISSUE THREAD

**Issue by chengzheng777** [umicro/uView2.0#130]
### 版本
2.0.9

### 转载链接
[kqt.hzzk.gov.cn/icon/](http://kqt.hzzk.gov.cn:60080/icon/#/)

### 重现步骤
全局初始话样式scss文件, 设置span标签 font-family: "Microsoft Yahei", sans-serif;。 然后 使用uview-ui的组件，包含图标部分就会变成小方框。

### 期望的结果是什么？
我不知道这算不算bug。因为是我自身配置问题。 希望有个说明不要全局配置 span 的 font-family？

### 实际的结果是什么？
全局配置span的font-family后失效

**Comment by MarkGor** [comment]
`
虽然不推荐使用HTML标签，但实际上如果开发者写了div等标签，在编译到非H5平台时也会被编译器转换为view标签，类似的还有span转text、a转navigator等，包括css里的元素选择器也会转。但为了管理方便、策略统一，新写代码时仍然建议使用view等组件。
`
uniapp官方是不建議直接使用html標籤，查看dom節點你就會發現，icon是設置uni-text的font-family,而你全局設置span是屬於uni-text下級，根據CSS優先級肯定是子元素生效。

**Comment by MarkGor** [comment]
類似這種需求，自己設置下 
.u-icon__icon > span{
    font-family: uicon-iconfont !important;
}
即可。

**Comment by chengzheng777** [comment]
> 类似这种需求，自己设置下 .u-icon__icon > span{ font-family: uicon-iconfont !important; } 即可。

好滴！万分感谢，解决了我的问题！！
