### ISSUE TITLE
安卓手机（已测试小米11和电脑模拟器）Swiper 轮播图 组件“radius 组件圆角”属性无效

### ISSUE THREAD

**Issue by GuangYuWen** [umicro/uView2.0#131]
### 版本
2.0.9

### 转载链接
[localhost](http://localhost:8081/pages/componentsC/swiper/swiper)

### 重现步骤
安卓手机打开有轮播图的页面，radius组件圆角无效，全是直角！

### 期望的结果是什么？
radius 组件圆角 有效

### 实际的结果是什么？
radius 组件圆角 无效，填入任何值都无效

**Comment by ChenLiuPng** [comment]
这个情况下可能2.0.11-12版本修复 目前已经修复
