### ISSUE TITLE
在cell单元格设置文本隐藏时，文本右边溢出

### ISSUE THREAD

**Issue by mhxw** [umicro/uView2.0#138]
### 版本
2.0.9

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/text.html#%E8%B6%85%E5%87%BA%E9%9A%90%E8%97%8F)

### 重现步骤
在cell单元格设置文本隐藏时，文本右边溢出
```
<u-cell-group :border="true" >
	<view  v-for="(item, index) in cardList" :key="index">
		<u-cell clickable @click="clickItem(item)" >
			<view slot="title" >
				<u--text :lines="1" :text="item.title" ></u--text>
			</view>
		</u-cell>
	</view>
</u-cell-group>
```

### 期望的结果是什么？
1. item.title 文本两侧均不溢出，右边末尾可显示省略号
2. cell 单元格添加功能：title 是否溢出隐藏，可选值，0:默认; 1:显示一行; 2:显示两行;
例如：https://uniapp.dcloud.io/component/uniui/uni-list?id=listitem-props

### 实际的结果是什么？
右边溢出

---
经过测试发现，cell组件中的这个class设置以下样式可解决溢出问题。
```
.u-cell__body__content {
	overflow: hidden;
}
```
但是，省略号测试发现，没有生效或者被影响，测试代码如下：
```
<u--text :text="item.title"  style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;display: inline-block;"></u--text>
```

**Comment by meng-ling-feng** [comment]
最好自己在css里处理

**Comment by BeiQiaoT** [comment]
这不应该由组件处理
