### ISSUE TITLE
Swiper卡片模式指定current为非默认值（0）时，被放大的总是第一个元素

### ISSUE THREAD

**Issue by Chinwer** [umicro/uView2.0#139]
### 版本
2.0.9

### 转载链接
[snipit.io](https://snipit.io/public/snippets/60826)

### 重现步骤
- 在页面中使用u-swiper组件，并在其中放置两个及以上的子组件
- 设置u-swiper的current属性为1（或其他任何非0的值）
- 设置u-swiper的前后previousMargin属性和nextMargin属性（也就是“卡片模式”）
- 运行程序，可以发现u-swiper的位置定位在第二个子组件，但是被放大的是第一个子组件

### 期望的结果是什么？
第一个子组件是缩小状态，第二个子组件是正常大小

### 实际的结果是什么？
第一个子组件是正常大小，第二个子组件是缩小状态

**Comment by Chinwer** [comment]
在 u-swiper 源码中，把
`data() { return { currentIndex: 0 } }`
改成
`data() { return { currentIndex: this.$props.current } }`

**Comment by orangepro11** [comment]
问题已确认
