### ISSUE TITLE
u-upload组件属性accept="video"时，微信小程序预览点击没有反应

### ISSUE THREAD

**Issue by Kchengz** [umicro/uView2.0#141]
### 版本
2.0.9

### 转载链接
[www.uviewui.com](https://www.uviewui.com/common/weixin_mini_qrcode.png)

### 重现步骤
扫描官方微信小程序二维码 -》 upload上传 -》 点击上传视频组件，无任何反应

### 期望的结果是什么？
能选择或拍摄视频

### 实际的结果是什么？
无反应

**Comment by ChenLiuPng** [comment]
我使用ios 无法复现

**Comment by yatoku** [comment]
我使用小米k30无法复现，请更新uview版本

**Comment by lj350201364** [comment]
华为MATE30 也没反应 是不是鸿蒙系统的原因？

**Comment by Kchengz** [comment]
> 我使用小米k30无法复现，请更新uview版本

更新到u-view 2.0.19版本，就可以了
