### ISSUE TITLE
阻止事件传播属性stop错误（控制台报错：WAServiceMainContext.js:2 TypeError: this.$u.preventEvent is not a function）

### ISSUE THREAD

**Issue by LaoHu97** [umicro/uView2.0#142]
### 版本
2.0.9

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/icon.html)

### 重现步骤
u-icon添加stop属性

### 期望的结果是什么？
阻止事件传播

### 实际的结果是什么？
报错

**Comment by orangepro11** [comment]
问题已确认，将在2.0.21版本修复
