### ISSUE TITLE
分段器组件的bug

### ISSUE THREAD

**Issue by gscwj** [umicro/uView2.0#144]
### 版本
2.0.9

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/intro.html)

### 重现步骤
打开uview2.0官网，然后找到介绍内的右侧手机模拟框，在里面找到组件分段器的示例，进行切换时，第一行的tab激活样式并未覆盖全，有空隙

### 期望的结果是什么？
无缝隙

### 实际的结果是什么？
有缝隙

**Comment by ChenLiuPng** [comment]
浏览器 调整窗口比例 会出现这种问题，手机上暂时没出现这种情况
