### ISSUE TITLE
u-image slot 加载和错误的图片失去了高度  小程序

### ISSUE THREAD

**Issue by unclemin** [umicro/uView2.0#146]
### 版本
2.0.10

### 转载链接
[http://192.168.171.237:8080/](http://192.168.171.237:8080)

### 重现步骤
	<u-image
				width="90"
				height="90"
				:src="goodsItem.main_images + '?style=w400'"
				radius="6"
				:fade="false"
			>
				<u-icon slot="loading" name="/static/icon/err.png" size="38"></u-icon>
				<u-icon slot="error" name="/static/icon/err.png" size="38"></u-icon>
			</u-image>

### 期望的结果是什么？
<view
				v-if="showError && isError && !loading"
				class="u-image__error"
				:style="{
					width: $u.addUnit(width),
					height: $u.addUnit(height),
					borderRadius: shape == 'circle' ? '50%' : $u.addUnit(borderRadius)
				}"
			>

### 实际的结果是什么？
<view
				v-if="showError && isError && !loading"
				class="u-image__error"
				:style="{
					borderRadius: shape == 'circle' ? '50%' : $u.addUnit(borderRadius)
				}"
			>

**Comment by orangepro11** [comment]
问题已确认，将在2.0.21修复
