### ISSUE TITLE
list组件只能单独使用，不能与其他组件一块使用

### ISSUE THREAD

**Issue by moxuandi** [umicro/uView2.0#147]
### 版本
2.0.10

### 转载链接
[localhost](http://localhost:8080/pages/study/poetry/list)

### 重现步骤
比如在列表顶部加一个搜索框（Search 搜索），或者加一个（Empty 内容为空），都会导致列表无法上滑，只能显示1屏

```
<u-empty  mode="car" icon="http://cdn.uviewui.com/uview/empty/car.png" />
<u-list class="poetry-list" @scrolltolower="scrolltolower">
      <u-list-item v-for="(item, index) in list" :key="index">
       ……
      </u-list-item>
</u-list>
```

### 期望的结果是什么？
正常下滑

### 实际的结果是什么？
无法下滑

---
导致现在列表页只有列表，无法添加其他元素

**Comment by yatoku** [comment]
可以给`list`组件，指定`height`属性。

**Comment by yatoku** [comment]
#149
