### ISSUE TITLE
2.0 的datetimePicker 通过v-model绑定值到input的时候是时间戳

### ISSUE THREAD

**Issue by LiaoShuaiAcount** [umicro/uView2.0#156]
### 版本
2.0.10

### 转载链接
[localhost/](http://localhost:8001/#/pages/index/index)

### 重现步骤
一个 input 一个datatimePicker ，都绑定相同的v-model值。datatimePicker 的@confirm时事件拿到选择到的回调参数为e。使用e.value获取到时间戳。将时间戳转为 yy-MM-dd 格式，重新赋值给 v-model绑定。然后结果input显示的还是时间戳，而控制台打印是正常的年月日格式。

### 期望的结果是什么？
让input 也显示年月日

### 实际的结果是什么？
显示的时间戳

---
业务场景 选择时间 赋值到input框。 input 是disabled的状态

**Comment by LiaoShuaiAcount** [comment]
解决办法：

**Comment by yatoku** [comment]
你可以写一个计算属性，get是把input的值转成时间戳，set是把datatimePicker的值转成年月日赋值给input的值
