### ISSUE TITLE
upload组件获取文件后文件原有属性丢失

### ISSUE THREAD

**Issue by hanson0824** [umicro/uView2.0#157]
### 版本
2.0.10

### 转载链接
[http://localhost:88/#/](http://localhost:88/#/)

### 重现步骤
上传文件后只能获取到url属性，其他文件属性拿不到

### 期望的结果是什么？
能够拿到文件原有属性

### 实际的结果是什么？
原有属性拿不到

---
原因是utils中方法pickExclude在判断uni.$u.test.object(obj)是出现问题，实际结果是[object File]

**Comment by orangepro11** [comment]
已修复完成
