### ISSUE TITLE
2.0 使用v-if 和 v-else 展示切换两个u--textarea会出问题

### ISSUE THREAD

**Issue by LiaoShuaiAcount** [umicro/uView2.0#158]
### 版本
2.0.10

### 转载链接
[http://localhost:8080/](http://localhost:8080/)

### 重现步骤
<u--textarea " v-if="detailModify" :disabled="true" v-model="currItem.remark" placeholder="请输入内容" ></u--textarea>
<u--textarea " v-else v-model="detailModel.remark" placeholder="请输入内容" ></u--textarea>
更改第二个文本域的值，第一个也会变动.
currItem和detailModel 是两个不同的对象。当我通过点击设置detailModify 为 false，第二个文本域就出来了，然后修改内容。
又通过一个按钮点击设置detailModify 为 true。这时切换到第一个文本域，发现其内容变了

### 期望的结果是什么？
两个文本域的值毫无关联

### 实际的结果是什么？
两个文本域的值关联到一起了

---
业务详情：有个文本域默认是不可编辑，当我点击修改按钮，切换到另一个可编辑的文本域，通过 v-if 来控制。
修改可编辑文本域的值，修改完了以后，不保存数据，直接通过按钮切换v-if的值 切换回禁用的文本域，其内容要求还是修改前的内容。

问题： 实际上，前者不可编辑的文本域值发生改变了

**Comment by BeiQiaoT** [comment]
这本质上是vue的dom复用，你尝试使用v-show,或者给input绑定 :key，这并不是组件的bug
