### ISSUE TITLE
什么时候支持vue3

### ISSUE THREAD

**Issue by lrqnew** [umicro/uView2.0#159]
### 这个功能解决了什么问题？
支持vue3

### 你期望的 API 是怎样的？
支持vue3

**Comment by ChenLiuPng** [comment]
什么时候uniapp全面全面全面支持vue3  就支持vue3了

**Comment by orangepro11** [comment]
暂无此计划

**Comment by minxiang51574** [comment]
mark

**Comment by xbmlz** [comment]
可以使用 vk-uview-ui，同时支持vue2.x和vue3.x， 
https://vkuviewdoc.fsq.pub/

或者现成的框架，vite3.x + vue3 + pinia + vk-uview-ui + ucharts
https://github.com/venable-dev/venable-uniapp
