### ISSUE TITLE
uview2.0的样式影响的到页面布局

### ISSUE THREAD

**Issue by hujialianghuwei** [umicro/uView2.0#16]
使用tabbar之后 发现tabbar内部样式影响到我页面的布局。内部的几个css  影响页面
![image](https://user-images.githubusercontent.com/40708676/142140437-f516d83f-5109-49b4-91c5-3303f34bb002.png)
[](url)

切换组件
[
![image](https://user-images.githubusercontent.com/40708676/142145145-2c39a1f7-6836-48a8-a398-b0219de336b5.png)
](url)
![image](https://user-images.githubusercontent.com/40708676/142145232-d3dc81bb-b706-4429-8783-64c252acbdf9.png)

**Comment by zhouzyc** [comment]
插个眼

**Comment by zhouzyc** [comment]
每一个组件引入,都会有一份修改全局的样式

**Comment by BeiQiaoT** [comment]
问题正在着手处理

**Comment by BeiQiaoT** [comment]
已处理
