### ISSUE TITLE
numberBox 的 min 属性在官网文的档说明与实际代码不一致

### ISSUE THREAD

**Issue by jiangmaniu** [umicro/uView2.0#164]
### 版本
2.0.10

### 重现步骤
文档说明
![image](https://user-images.githubusercontent.com/50100681/145662533-8f3e0a5b-7b74-4f7d-af36-a46795395576.png)

实际代码
https://github.com/umicro/uView2.0/blob/19b02d47c68b4431064bb6ebbfe7f26e1a7863d0/uni_modules/uview-ui/libs/config/props/numberBox.js#L15

**Comment by ChenLiuPng** [comment]
好的 马上修复

**Comment by BeiQiaoT** [comment]
已处理
