### ISSUE TITLE
nvue  u-popup 组件关闭（隐藏）时，会先闪一下再关闭。

### ISSUE THREAD

**Issue by KiteWorld** [umicro/uView2.0#168]
### 版本
2.0.11

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/popup.html)

### 重现步骤
nvue  u-popup 组件关闭（隐藏）时，会先闪一下再关闭。

### 期望的结果是什么？
不要闪

### 实际的结果是什么？
会先闪一下再关闭

**Comment by KiteWorld** [comment]
找到了bug的原因，u-popup 封装用到了 u-overlay 组件，而 u-overlay 本质上还是调用了u-transition, 把 duration 过渡时间设置为0可以解决。但不可避免得遮罩隐藏也会没有过渡效果。这是一个折衷得解决办法。 更深层的原因很可能跟 animation 动画有关。开发任务紧急，溜了溜了

**Comment by Liangzhihe** [comment]
同样的问题，官方准备什么时候修复？

**Comment by Funnyboycode** [comment]
u-overlay 动画时间比u-u-transition的长一些就可以了。相同的话会导致背景消失了但是里面的内容还没有消失。给人一种闪一下的感觉。
![image](https://user-images.githubusercontent.com/46807943/149927440-727c7699-e4de-48e9-901b-b1a32f9e127a.png)

**Comment by orangepro11** [comment]
问题已确认，将在2.0.23版本修复
