### ISSUE TITLE
nvue u--textarea 字数统计无效，输入值，数量没有变化；height 属性无效。

### ISSUE THREAD

**Issue by KiteWorld** [umicro/uView2.0#169]
### 版本
2.0.11

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/textarea.html)

### 重现步骤
```
<u--textarea border="none" placeholder="请输入补充内容" autoHeight maxlength="180" :height="200" count trim></u--textarea>

```
### 期望的结果是什么？
height  和 字数统计有效

### 实际的结果是什么？
无效

**Comment by BeiQiaoT** [comment]
请绑定v-model使用
<u--textarea v-model="value" border="none" placeholder="请输入补充内容" autoHeight maxlength="180" :height="200" count trim></u--textarea>
