### ISSUE TITLE
wx 小程序上自定义 class 选择器不生效

### ISSUE THREAD

**Issue by Monseter** [umicro/uView2.0#174]
### 这个功能解决了什么问题？
<u-row  class="custom-row"></u-row>
这里自定义 class 类名用于自己写样式进行控制

### 你期望的 API 是怎样的？
可以自定义 class 类名用于自己写样式进行控制

**Comment by orangepro11** [comment]
通过custom-style传入样式

**Comment by zhaotoday** [comment]
@orangepro11 感觉新增一个 custom-class 会更好点。

**Comment by xingkoo** [comment]
我需要通过一个父类来统一管理下面的类，所以确认有个`custom-class`可能会更好一些。
