### ISSUE TITLE
swiper组件卡片式轮播在字节小程序中没有3d效果，没有边距

### ISSUE THREAD

**Issue by 875908494** [umicro/uView2.0#183]
### 版本
2.0.9

### 转载链接
[localhost/](http://localhost:8080/#/pages/index/index)

### 重现步骤
首页直接显示

### 期望的结果是什么？
希望在字节小程序中能够正常显示

### 实际的结果是什么？
在字节小程序中没有边距，全部挨在一起，切换没有3d效果

---
<u-swiper :list="list3" previousMargin="100" nextMargin="100" height="200" circular :autoplay="true"
				radius="5" bgColor="#ffffff"></u-swiper>

**Comment by yatoku** [comment]
你可以尝试使用uniapp的swiper看看，如果uniapp的没有适配字节小程序的话，那就是uniapp中swiper的问题。因为uview的swiper组件也是再次封装uniapp的swiper实现的

**Comment by saberonthemic** [comment]
微信小程序也不生效
