### ISSUE TITLE
2.0.13 版本 u-tabbar 组件设置border属性无效，u-border-top内置class样式未生效

### ISSUE THREAD

**Issue by silencyXiao** [umicro/uView2.0#189]
### 版本
2.0.13

### 转载链接
[localhost/](http://localhost:8080/#/pages/index/index)

### 重现步骤
2.0.13 版本 引用u-tabbar组件，border上边框失效

### 期望的结果是什么？
u-tabbar 配置border时出现上边框

### 实际的结果是什么？
没有上边框

---
border配置是没问题的，原因是u-border-top内置class样式未生效

**Comment by ChenLiuPng** [comment]
使用!important试一试

**Comment by yatoku** [comment]
可能是你没有在app.vue中引入uview的公共样式文件
