### ISSUE TITLE
【新增需求】给 u--input 的输入框添加点击事件，这个应用场景还蛮多的

### ISSUE THREAD

**Issue by KiteWorld** [umicro/uView2.0#191]
### 这个功能解决了什么问题？
u--input（disabled 或者 readonly 为 true） 用作选择下拉框时候很需要。

### 你期望的 API 是怎样的？
<u--input @click-input="clickInput"></u-input>

**Comment by orangepro11** [comment]
可以使用@input.native="inputHandler"

**Comment by Hyachin** [comment]
> 可以使用@input.native="inputHandler"

作为选择下拉框，disabled 或者 readonly 时，不会触发input事件
