### ISSUE TITLE
日历组件无法设置默认日期区间为今天之前的日期

### ISSUE THREAD

**Issue by HaoranranWang** [umicro/uView2.0#193]
### 版本
2.0.13

### 转载链接
[http://localhost:8080/](http://localhost:8080)

### 重现步骤
设置默认日期为今天之前的日期不行，设置今天及以后可以，例如默认日期区间是：2012-12-01到2021-12-25，只会展示2021-12-25为开始日期，设置了min-date和max-date也不行

### 期望的结果是什么？
希望可以任意设置日期区间

### 实际的结果是什么？
并不能设置任意日期为默认日期

**Comment by yatoku** [comment]
可以设置一下minDate，现在源码中如果没有设置minDate的话，最小时间就会是当下时间，导致你内容没有显示。然后如果你minDate和maxDate都没有设置的话，就是当前时间到三个月后。
