### ISSUE TITLE
u-sticky 出现多余默认值 customNavHeight

### ISSUE THREAD

**Issue by yangqi12345** [umicro/uView2.0#194]
### 这个功能解决了什么问题？
解决了u-sticky在H5顶部出现多余top，H5本身有导航栏，默认为0才是最好的；需要自定义导航栏的再自己去设置才是正常逻辑

### 你期望的 API 是怎样的？
解决了u-sticky在H5顶部出现多余top，H5本身有导航栏，默认为0才是最好的；需要自定义导航栏的再自己去设置才是正常逻辑

` // 自定义导航栏的高度
        customNavHeight: {
            type: [String, Number],
            // #ifdef H5
            // H5端的导航栏属于“自定义”导航栏的范畴，因为它是非原生的，与普通元素一致
            default: 44,
            // #endif
            // #ifndef H5
            default: uni.$u.props.sticky.customNavHeight
            // #endif
        },`

**Comment by orangepro11** [comment]
请把代码作为PR提出
