### ISSUE TITLE
button组件中文字不显示

### ISSUE THREAD

**Issue by yueqiqi** [umicro/uView2.0#2]
button组件在nvue中，文字不显示

**Comment by tttao7** [comment]
麻烦带上机型 Android/iOS 并贴一下代码或截图 方便我们排查

**Comment by yueqiqi** [comment]
#### 按钮能显示就是文字显示不出来
![HN3@1)DB_VMTTWIMNR{8 VG](https://user-images.githubusercontent.com/50952334/141935307-c5e23ef6-24f9-4897-a5ca-4b7faa2c1db3.png)
![da4d6be8e7656ae9d68c076beee2272](https://user-images.githubusercontent.com/50952334/141935374-be993304-9926-463d-956d-cf9e7856cde3.jpg)
![07cd94e67bb564ac706b295f5da5a46](https://user-images.githubusercontent.com/50952334/141935391-508bf7cd-4deb-4597-8a90-2148b561e955.jpg)

**Comment by tttao7** [comment]
此问题为文档问题，正确用法如下：
`<u-button text="按钮"></u-button>`

在nvue下，不能控制通过slot传入内容的样式，也就是说无法修改文字颜色和大小，因为nvue的text文本无法继承父元素的样式，只能把样式明确给到某个text组件。而slot传入的内容，不属于任何一个text元素，所以无法控制样式。
