### ISSUE TITLE
icon 组件的字体文件，在app端有没有从static目录下引入的计划？

### ISSUE THREAD

**Issue by iamxcd** [umicro/uView2.0#219]
### 这个功能解决了什么问题？
我修改本地文件，css下通过 url("statci/xxx")的方式，能正常展示字体，解决首页进入，图标会延迟展示的问题。

### 你期望的 API 是怎样的？
但是更新uview版本后，本地的调整被覆盖，我能提一个合并请求吗

**Comment by ChenLiuPng** [comment]
nvue情况下呢

**Comment by iamxcd** [comment]
> 

nvue 这个没有使用,没有测试 条件编译APP-VUE 这样处理的

**Comment by ChenLiuPng** [comment]
nvue暂时找不到方法实现 只能搁置了

**Comment by orangepro11** [comment]
此需求暂时无法满足，受限于nvue
