### ISSUE TITLE
需求：Tabbar是否能和1.0一样增加中间凸起功能

### ISSUE THREAD

**Issue by 0xZzOrz** [umicro/uView2.0#220]
### 这个功能解决了什么问题？
凸起按钮醒目代表主要功能

### 你期望的 API 是怎样的？
需求：Tabbar是否能和1.0一样增加中间凸起功能

**Comment by ChenLiuPng** [comment]
这个tabbar 挺坑的这玩意 产品设计就不应该有这玩意 使用原生tabbar最好

**Comment by gulullu** [comment]
同求 mid-button 属性

**Comment by hzh1990** [comment]
自己把Tabbar改改行不行?

**Comment by orangepro11** [comment]
nvue的css受限，凸起不好做，也不建议做凸起

**Comment by ILfengzi** [comment]
> nvue的css受限，凸起不好做，也不建议做凸起

中间凸起这个需求还是挺常见的，不知能否先提供小程序版本的？

**Comment by yangbin11** [comment]
同求 mid-button 属性

**Comment by sunpm** [comment]
小程序能否加上去呢，不使用 nvue 行不行

**Comment by ILfengzi** [comment]
已收到！
