### ISSUE TITLE
微信小程序分包时, u-loading-page在子包里使用会报错未找到组件, 需要手动引入

### ISSUE THREAD

**Issue by huchengyong** [umicro/uView2.0#228]
### 版本
2.0.18

### 转载链接
[http://localhost/](http://localhost)

### 重现步骤
1. 给uni-app项目分包, 子包根目录为subPages
2. 在子包里创建一个组件使用u-loading-page
3. 编译预览时会报错找不到u-loading-page组件(需要手动引入)

### 期望的结果是什么？
希望在子包里也能自动加载组件

### 实际的结果是什么？
需要手动引入才能加载组件

**Comment by orangepro11** [comment]
这个需要提给DCloud官方
