### ISSUE TITLE
form表单校验功能在小程序某些版本中报错

### ISSUE THREAD

**Issue by sunrist1** [umicro/uView2.0#231]
### 版本
2.0.19

### 转载链接
[http://localhost/](http://localhost/)

### 重现步骤
使用uview2.0.19版本，运行成小程序(基础库2.14.1及以下版本)
form表单，加上校验功能

<u--form labelPosition="left" :borderBottom="false" :model="model1" :rules="rules" ref="form1" labelWidth="100">
			<u-form-item label="手机号码" prop="userInfo.phone" :borderBottom="false" ref="item1" :required="true">
				<u--input v-model="model1.userInfo.phone" border="none" type="number" placeholder="点击输入"></u--input>
			</u-form-item>
			<u-form-item label="短信验证码" prop="userInfo.code" :borderBottom="false" ref="item1" :required="true">
				<u--input v-model="model1.userInfo.code" border="none" placeholder="点击输入"></u--input>
				<view class="code-tips" slot="right" @tap="getCode" :disabled="disabled1">
					{{tips}}
				</view>
			</u-form-item>
		</u--form>

onReady() {
			this.$refs.form1.setRules(this.rules)
		},

会报错TypeError: Cannot read property 'setRules' of undefined
form表单的其他校验相关函数均报错(如validate)，若把小程序基础库调整成(2.14.1版本以上，则无报错)

### 期望的结果是什么？
在低版本基础库中也可实现正常校验

### 实际的结果是什么？
校验函数报错

**Comment by hzh1990** [comment]
TypeError: Cannot read property 'setRules' of undefined

提示很明显了。

**Comment by orangepro11** [comment]
把小程序的基础版本库升级到2.19.2，具体参考https://www.kancloud.cn/uview/uview-ui_v2/2579076
