### ISSUE TITLE
Cell 单元格 浏览器控制台有报错

### ISSUE THREAD

**Issue by gooking** [umicro/uView2.0#232]
### 版本
2.0.19

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/cell.html)

### 重现步骤
<u-cell icon="setting-fill" title="个人设置"></u-cell>

然后查看浏览器控制台

### 期望的结果是什么？
无报错

### 实际的结果是什么？
[Vue warn]: Invalid default value for prop "titleStyle": Props with type Object/Array must use a factory function to return the default value.

found in

---> <UCell> at uni_modules/uview-ui/components/u-cell/u-cell.vue
       <UCellGroup> at uni_modules/uview-ui/components/u-cell-group/u-cell-group.vue

**Comment by yatoku** [comment]
问题已修复
