### ISSUE TITLE
ios真机模式 u--input type=number type= digit 无效

### ISSUE THREAD

**Issue by chenjibin** [umicro/uView2.0#237]
### 版本
2.0.19

### 转载链接
[xn--%20ios-1j4m636ho72bena/](http:// ios真机调试)

### 重现步骤
ios真机调试用 u--input 组件设置type为number 或者digit 

### 期望的结果是什么？
弹出数字键盘

### 实际的结果是什么？
还是type为text的键盘

---
ios版本15.2
用nvue原生组件input设置type为number或者digit是有效的

**Comment by YanxinNet** [comment]
已处理，github已更新，下个版本2.0.20推送修复
