### ISSUE TITLE
u-sticky组件 offsetTop吸顶距离单位默认是px而不是rpx 这是bug，uni.$u.config.unit = 'rpx'设置也无效

### ISSUE THREAD

**Issue by Wuou** [umicro/uView2.0#238]
### 版本
2.0.19

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/sticky.html)

### 重现步骤
u-sticky组件 offsetTop吸顶距离单位默认是px而不是rpx 这是bug，uni.$u.config.unit = 'rpx'设置也无效

### 期望的结果是什么？
期望是rpx数值

### 实际的结果是什么？
实际是px数值

**Comment by Wuou** [comment]
![image](https://user-images.githubusercontent.com/14285500/147716603-560c4e8e-6e9b-402f-891d-3d66b8d73fd9.png)

**Comment by Wuou** [comment]
修改后的代码：
![image](https://user-images.githubusercontent.com/14285500/147717345-15d284d0-249d-49c9-9879-ca0544cdc63b.png)

**Comment by yatoku** [comment]
感觉反馈

**Comment by yatoku** [comment]
感谢反馈

**Comment by YanxinNet** [comment]
问题已处理，改为使用uni.$u.getPx去获取值的单位了，下个版本更新

**Comment by MrChenGG** [comment]
我现在使用2.0.36设置unit='rpx' 也是不生效的 u-button 都还是px单位
