### ISSUE TITLE
u-silder没有disabled属性

### ISSUE THREAD

**Issue by Pizhong** [umicro/uView2.0#239]
### 这个功能解决了什么问题？
需求是展示滑块进度，用户不可以自行滑动模块。需要禁用滑动
补充：组件文档上是有disabled的，但源码中没有看到对应的props属性

### 你期望的 API 是怎样的？
``` html
<u-slider v-model="value" disabled></u-slider>
```

**Comment by yatoku** [comment]
暂时可以先参考我提交的PR

**Comment by yatoku** [comment]
2.0.20版本已修复
