### ISSUE TITLE
u-tabs

### ISSUE THREAD

**Issue by huangrenyi** [umicro/uView2.0#24]
1.当tabs 定义list数组为空时，再去接口请求数据赋值list数组  下滑快会往左偏移切换tabs后则正常了
2.current 定义为2 ，tabs还是在默认0，动态切换current 也没有变化
3.name属性没有作用

**Comment by BeiQiaoT** [comment]
tabs问题列入清单，在准备解决

**Comment by BeiQiaoT** [comment]
已处理

**Comment by EarhartZhao** [comment]
u-tabs的keyName字段无效，源码中也未找到props处理
