### ISSUE TITLE
u-sticky组件在h5下，顶部会有很大的空白

### ISSUE THREAD

**Issue by gooking** [umicro/uView2.0#243]
### 版本
2.0.19

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/sticky.html)

### 重现步骤
h5环境下，顶部存在空白空间

### 期望的结果是什么？
没有空间

### 实际的结果是什么？
有空间

**Comment by gooking** [comment]
"navigationStyle": "custom",

的情况下才会出现的

**Comment by hzh1990** [comment]
代码不贴，图片不贴。
还想别人回答你？

**Comment by gooking** [comment]
pages.json:
`
{
		  "path" : "pages/test/test",
		  "style": {
		"navigationStyle":"custom"
		  }
}
`

测试页面 test.vue

`
<template>
	<view class="test">
		<u-sticky>
			<view class="top"></view>
		</u-sticky>
		<view class="top2"></view>
	</view>
</template>

<style scoped lang="scss">
.test {
	.top {
		height: 88rpx;
		background-color: green;
	}
	.top2 {
		height: 300rpx;
		background-color: red;
	}
}
</style>

`


效果如下，h5，谷歌浏览器调试（顶部有白色空白）：

![image](https://user-images.githubusercontent.com/7286469/149602465-aa74b608-d874-434b-9b46-473d890643d8.png)


本测试已经下载了最新版本的uview2.0代码（2022-01-14日更新的）

**Comment by gooking** [comment]
![image](https://user-images.githubusercontent.com/7286469/149602494-4eee0757-9879-46e0-b130-3d60e0609ce0.png)

**Comment by gooking** [comment]
如果不加 u-sticky ，那么头部是不会出现那个白色的区域的，绿色区块会顶住头部。但是只要加了 u-sticky ，头部就会有一块白色的区块出来

**Comment by yatoku** [comment]
设置一下`customNavHeight`这个属性，因为它在H5中默认是44px。
