### ISSUE TITLE
使用leftwindow时候，引用组件会导致报错uni is not defined

### ISSUE THREAD

**Issue by 81549361** [umicro/uView2.0#253]
### 版本
2.0.19

### 转载链接
[ask.dcloud.net.cn](https://ask.dcloud.net.cn/question/137485?column=log&rf=false)

### 重现步骤
使用leftwindow时候，leftwindow.vue中，先引用内容页面，在内容页面引用uni_modules中的组件

会导致白屏，报错uni is not defined

### 期望的结果是什么？
正常运行

### 实际的结果是什么？
白屏

---
示例见重现链接

**Comment by orangepro11** [comment]
bug确认，此问题只能交给DCloud官方修复
