### ISSUE TITLE
SwipeAction组件click事件无效

### ISSUE THREAD

**Issue by yum-sky** [umicro/uView2.0#255]
### 版本
2.0.19

### 转载链接
[localhost](http://localhost:8081/pages/componentsA/swipeAction/swipeAction)

### 重现步骤
<u-swipe-action @click="click()"> 添加点击事件

### 期望的结果是什么？
能够正常响应点击事件

### 实际的结果是什么？
不能够正常响应点击事件

**Comment by weiguanglai** [comment]
新手？@click="click"

**Comment by orangepro11** [comment]
文档错误，把click事件加到swipe-action-item上即可。
