### ISSUE TITLE
scrollview嵌套list在小程序端无法下拉刷新

### ISSUE THREAD

**Issue by qiujunyu** [umicro/uView2.0#258]
### 这个功能解决了什么问题？
因为list上面还有搜索框，不想用页面级的下拉刷新

### 你期望的 API 是怎样的？
小程序端，scrollview嵌套list也能正常下拉刷新

**Comment by weiguanglai** [comment]
走错地方了吧，scrollview 不是小程序的原生组件么。怎么跑这来提问

**Comment by yatoku** [comment]
`list`组件内部，在非`app-nvue`的环境下，使用的就是`scroll-view`，你可以试试`scroll-view`嵌套`scroll-view`
