### ISSUE TITLE
APP中，u-popup大概率收縮時會產生閃爍

### ISSUE THREAD

**Issue by MarkGor** [umicro/uView2.0#26]
mode指定top|bottom時，
APP中大概率出現收縮後閃爍一下的情況
比如當mode為top時候，
關閉時候popup會向上收，當收完的時候會自動彈出閃爍一下再隱藏。
H5下沒有這個情況，
測試機型華為mate30p

**Comment by BeiQiaoT** [comment]
好的，我们记录一下说

**Comment by Liangzhihe** [comment]
APP端mode设置为left|right时也遇到同样的问题，测试机型为小米10pro，新版本会修复么？

**Comment by MarkGor** [comment]
> APP端mode设置为left|right时也遇到同样的问题，测试机型为小米10pro，新版本会修复么？

不知道什麼原因導致的，解決方式是nvue禁用收起動畫，這樣就不會導致閃爍了。

**Comment by Liangzhihe** [comment]
> > APP端mode设置为left|right时也遇到同样的问题，测试机型为小米10pro，新版本会修复么？
> 
> 不知道什麼原因導致的，解決方式是nvue禁用收起動畫，這樣就不會導致閃爍了。

谢谢，试了一下，禁用动画会导致弹出框的出现和消失比较突兀，只能算是两权相害取其轻，期待官方尽早修复吧

**Comment by Funnyboycode** [comment]
https://github.com/umicro/uView2.0/issues/168#issuecomment-1015312833
