### ISSUE TITLE
app.vue中使用路由转跳会机率性成功

### ISSUE THREAD

**Issue by gm-fire** [umicro/uView2.0#264]
### 版本
2.0.19

### 转载链接
[route](https://www.uviewui.com/js/route.html)

### 重现步骤
onLaunch或onShow下使用uni.$u.route,然后用xcode的模拟器运行.发现经常无法跳转.加延时都不行,用uni.redirectTo就没问题.

### 期望的结果是什么？
打开页面可以跳转

### 实际的结果是什么？
打开页面机率性成功跳转

**Comment by yatoku** [comment]
因为在app.vue中可能main.js加载的全局变量可能还没有初始化完成，所以uni.$u可能还不存在。如果实在需要在app.vue里使用的话，建议还是用uni的API进行跳转。
