### ISSUE TITLE
npm包里没有自带字体吗？还要外网下载吗？

### ISSUE THREAD

**Issue by kping** [umicro/uView2.0#265]
### 这个功能解决了什么问题？
我可以在互联网环境开发，但运行是在内网，这个字体能集成在npm包里吗

### 你期望的 API 是怎样的？
在内网运行图标都没有

**Comment by kping** [comment]
内网环境没有互联网

**Comment by ChenLiuPng** [comment]
暂时可以先下载下来引用。用的iconfont的链接

**Comment by ChenLiuPng** [comment]
收到这个建议。

**Comment by kping** [comment]
好的 谢谢
