### ISSUE TITLE
【Feature】希望search组件能暴露点击左边icon事件

### ISSUE THREAD

**Issue by Xyuan-abs** [umicro/uView2.0#267]
### 这个功能解决了什么问题？
暴露 search组件点击左边icon事件，用于左边icon为扫码icon时，点击触发扫码

### 你期望的 API 是怎样的？
@click-icon

**Comment by ChenLiuPng** [comment]
恩恩，收到！

**Comment by orangepro11** [comment]
已添加，更新到2.0.20即可
