### ISSUE TITLE
Album单张图片无法显示

### ISSUE THREAD

**Issue by Pizhong** [umicro/uView2.0#268]
### 版本
2.0.19

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/album.html)

### 重现步骤
```
<u-album
  :urls="file_urls"
  single-size="184"
  multiple-size="88"
/>
file_urls: [
  'https://cdn.uviewui.com/uview/album/1.jpg',
],
```

### 期望的结果是什么？
![https://raw.githubusercontent.com/Pizhong/PicGoImg/main/202201101702374.png](https://raw.githubusercontent.com/Pizhong/PicGoImg/main/202201101702374.png)

### 实际的结果是什么？
![https://raw.githubusercontent.com/Pizhong/PicGoImg/main/202201101703646.png](https://raw.githubusercontent.com/Pizhong/PicGoImg/main/202201101703646.png)

**Comment by ChenLiuPng** [comment]
什么环境下？都会吗？

**Comment by Pizhong** [comment]
目前使用的是小程序和H5，发现都会出现这种情况

**Comment by abbyehl** [comment]
加个keyName试一下 
<u-album :urls="[{src2: item.fileUrl}]" mode="scaleToFill" keyName="src2" width="100px" height="80px"></u-album>

**Comment by abbyehl** [comment]
:urls="[{src2: item.fileUrl}]" 
mode="scaleToFill" keyName="src2"
width="100px"
height="80px"

**Comment by Pizhong** [comment]
> :urls="[{src2: item.fileUrl}]" mode="scaleToFill" keyName="src2" width="100px" height="80px"

这种写法是可以的，但就需要对图片数组长度为1做单独处理了

**Comment by orangepro11** [comment]
已修复，更新到2.0.20试试
