### ISSUE TITLE
2.0日历组件无法使用，仅能展示3个月的数据，无法切换年份月份

### ISSUE THREAD

**Issue by Steven-Yung** [umicro/uView2.0#271]
### 版本
2.0.19

### 转载链接
[www.uviewui.com](https://www.uviewui.com/common/weixin_mini_qrcode.png)

### 重现步骤
运行demo或微信扫小程序二维码体验，打开日历组件，只能展示2022年1-3月的数据，并且无法切换年和月，还是半成品？？？

### 期望的结果是什么？
可以展示任何完整的年月数据，切换年月

### 实际的结果是什么？
只能展示2022年1-3月的数据，并且无法切换选择其他年/月

**Comment by yatoku** [comment]
设计如此，如果想要切换年月的话 可以自己定义minDate和maxDate 设置数额较大的monthNum

**Comment by Steven-Yung** [comment]
> 设计如此，如果想要切换年月的话 可以自己定义minDate和maxDate 设置数额较大的monthNum

设置minDate,maxDate,monthNum都无效，跟没设置的时候一样，还是只有1-3月，无法展示和选择其他日期，比如我想选2021-12-01就无法选择，因为你无法切换到2021年的日历去，您可以打开你们的demo试试看，或者加我QQ356586162交流下，我在群里反馈没有得到回应，我是真的很需要这个日历

https://user-images.githubusercontent.com/8358206/149052527-758cb064-58fb-44a2-add1-65541fb39b3f.mp4

**Comment by yatoku** [comment]
因为demo里的没有设置啊- - 如果要设置到之前的年月 就需要设置minDate加上maxDate和monthNum不然的话就不行 如果需要切换多年的话 可以选择插件市场上别的日历组件
