### ISSUE TITLE
Popup 弹出层无法设置borderRadius

### ISSUE THREAD

**Issue by joney888999** [umicro/uView2.0#278]
### 版本
2.0.20

### 转载链接
[localhost/](http://localhost:8085/#/pages/post/post3)

### 重现步骤
使用如下代码
<u-popup :show="show" mode="center" :borderRadius="50" @close="close">
</u-popup>
在浏览器中无法解析borderRadius属性
<uni-view data-v-3a231fda="" data-v-073b7334="" class="u-popup" borderradius="50"></uni-view>

### 期望的结果是什么？
borderRadius能正常解析

### 实际的结果是什么？
borderRadius不能正常解析

**Comment by yatoku** [comment]
目前是使用`round`属性设置弹窗的圆角值的，`borderRadius`无效是文档错误导致的。
