### ISSUE TITLE
可以放一个集成好的2.0版本的空项目吗？类似于1.x版本中的空项目，方便开箱即用

### ISSUE THREAD

**Issue by yangshifeng666** [umicro/uView2.0#280]
### 这个功能解决了什么问题？
不能重复性的去搭建空项目创建工程，类似于1.x版本中的空项目，方便开发者，开箱即用

### 你期望的 API 是怎样的？
减少开发者的，重复性工作，开箱即用，简化开发

**Comment by yatoku** [comment]
已经有人在做了，后续应该会放出来，快了。

**Comment by yatoku** [comment]
https://www.npmjs.com/package/uview-cli
