### ISSUE TITLE
对qq小程序的兼容不够好

### ISSUE THREAD

**Issue by gitldx2** [umicro/uView2.0#282]
### 这个功能解决了什么问题？
目前试用了一下 Form 表单,layout 布局,Grid 宫格布局，在qq小程序下都没效果。
其中Form 表单验证无效，布局也无效；layout 布局,Grid 宫格布局这两个也是布局无效，完全没有按照比例来布局。我估计其他类似有布局功能的组件可能在qq小程序下都有问题。

tabs ，Subsection的对齐布局也是无效的。貌似社区目前没有对qq小程序方面做过测试呀

### 你期望的 API 是怎样的？
兼容qq小程序

**Comment by yatoku** [comment]
如果想要兼容qq小程序的话建议使用uview1的版本，uview2主要是兼容nvue的。因为nvue特性的关系，目前主要只兼容了APP和微信小程序。
