### ISSUE TITLE
什么时候支持vue3, uniapp 已经全面支持vue3了

### ISSUE THREAD

**Issue by jzfai** [umicro/uView2.0#284]
### 这个功能解决了什么问题？
uview2.0还没支持vue3

### 你期望的 API 是怎样的？
uview2.0尽快支持vue3

**Comment by BeiQiaoT** [comment]
这个可能需要等等，目前为止，uview2.0还是有很多需要解决的bug，等uview处于稳定之后，我们在进行vue3的适配工作

**Comment by xbmlz** [comment]
可以使用 vk-uview-ui，同时支持vue2.x和vue3.x， 
https://vkuviewdoc.fsq.pub/

或者现成的框架，vite3.x + vue3 + pinia + vk-uview-ui + ucharts
https://github.com/venable-dev/venable-uniapp
