### ISSUE TITLE
由于微信小程序中的组件都设置为虚拟的，virtualHost:true, 导致this.$refs失效，v-form的validateField等方法无法使用

### ISSUE THREAD

**Issue by mingweiyuning** [umicro/uView2.0#289]
### 版本
2.0.20

### 重现步骤

1. 定义一个v-form
 <u-form
          labelPosition="top"
          :model="consultContent"
          :rules="rules"
          ref="uForm"
        >
 </u-form>
2.   onReady() {
    this.$nextTick(()=>{
        console.log(this.$refs);
    }) 
  },
3. 微信小程序调试器中cosole输出{}

### 期望的结果是什么？
微信小程序调试器中console输出{uForm:vueComponent}

### 实际的结果是什么？
微信小程序调试器中console输出{}

---
由于uView2.0的自定义组件在微信小程序中都是虚拟的，所以在微信小程序中，ref无法加在v-form渲染出来的dom上面，导致this.$refs获取不到该v-form dom，所以无法使用v-form定义的function，例如validateField，setRules等

**Comment by orangepro11** [comment]
请把微信小程序基础版本库升级到2.19.2，这是小程序的bug，在此版本后已修复

**Comment by KiteWorld** [comment]
企业微信基础版本库 2.17 也有这个bug ,这是微信那边的bug ? 还是组件的bug。 我自己封装的组件 $refs 是可以获取到了
![image](https://user-images.githubusercontent.com/41134908/170821080-0f4bde66-253e-489d-ba04-26913b39e8b6.png)
