### ISSUE TITLE
u-index-list 组件插槽显示与否判断错误

### ISSUE THREAD

**Issue by junweiWu** [umicro/uView2.0#293]
### 版本
2.0.20

### 转载链接
[http://xx.com/](http://XX.com)

![image](https://user-images.githubusercontent.com/46172695/150070923-d9d77aa1-48dd-4ef0-aee3-92dd0a63829d.png)

### 重现步骤
u-index-list.vue 文件中的footer插槽 用了header 插槽是否存在来判断显示与否

### 期望的结果是什么？
无

### 实际的结果是什么？
无

**Comment by orangepro11** [comment]
问题已确认。

**Comment by orangepro11** [comment]
将在2.0.22版本修复
