### ISSUE TITLE
upload组件accept设置为video及media时，真机都无反应

### ISSUE THREAD

**Issue by maodou38** [umicro/uView2.0#307]
### 版本
2.0.21

### 转载链接
[http://xxxx/pages/index/index](http://XXXX/pages/index/index)

### 重现步骤
本人设备是iphone7
设置为media时，模拟器可以，真机不可以。设置为video时都不可以了

### 期望的结果是什么？
设置为video时可以点击生效，才能上传视频

### 实际的结果是什么？
无反应

**Comment by yatoku** [comment]
https://github.com/umicro/uView2.0/pull/446
