### ISSUE TITLE
Album 单张图片无法显示宽高

### ISSUE THREAD

**Issue by ReinhardChen93** [umicro/uView2.0#32]
![image](https://user-images.githubusercontent.com/43949619/142364501-a9e59ff9-32e1-418c-b5c9-5fe4d77ae8ab.png)

> 修改成这样才可以

`imageWidth() {

				return this.urls.length === 1 ? this.$u.addUnit(this.singleWidth) : this.$u.addUnit(this.multipleSize)
			},
			imageHeight() {
				
				return this.urls.length === 1 ? this.$u.addUnit(this.singleHeight) : this.$u.addUnit(this.multipleSize)
			},`

**Comment by BeiQiaoT** [comment]
已修复
