### ISSUE TITLE
datetimepicker组件更新后显示异常，排列乱序

### ISSUE THREAD

**Issue by qlspark** [umicro/uView2.0#324]
### 版本
2.0.25

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/datetimePicker.html)

### 重现步骤
datetimepicker组件更新后显示异常，排列乱序
![canvas](https://user-images.githubusercontent.com/32605539/151357505-eafc57e2-8a4e-42ab-bc74-9fe40df81ca4.png)

### 期望的结果是什么？
datetimepicker组件显示正常

### 实际的结果是什么？
datetimepicker组件更新后显示异常，排列乱序

**Comment by momoca** [comment]
https://github.com/umicro/uView2.0/issues/325

**Comment by orangepro11** [comment]
已在2.0.26修复
