### ISSUE TITLE
修复u-picker显示错误.

### ISSUE THREAD

**Issue by momoca** [umicro/uView2.0#325]
https://github.com/umicro/uView2.0/blob/f042873107f2e678b239fd78448eb284fd7c5ff2/uni_modules/uview-ui/components/u-picker/u-picker.vue#L257

fix:
```
display: block !important;
```

![2022-01-27_231203](https://user-images.githubusercontent.com/11501193/151387633-0d68f24c-0db9-4fb7-95f2-f58f717cb427.png)
![2022-01-27_231220_](https://user-images.githubusercontent.com/11501193/151387645-0c56c708-8415-43da-bf91-d1339c2c37f7.png)

**Comment by orangepro11** [comment]
已在2.0.26版本修复，此为修复tabs时出现的问题，现已回滚代码
