### ISSUE TITLE
Subsection 分段器 选中分段文字被遮挡

### ISSUE THREAD

**Issue by SGodV** [umicro/uView2.0#33]
uView版本 ：2.0.3
平台：h5
问题： Subsection 分段器active滑块叠放顺序有问题

![image](https://user-images.githubusercontent.com/37214323/142366799-4bf55c57-e24a-4e4c-a6fa-25ec62179c42.png)

解决方法：当前选中的段文字被遮挡，手动加上任意大于0的z-index可显示，如下图

![image](https://user-images.githubusercontent.com/37214323/142366981-8c24ced8-ae01-4049-9530-c8785d050c32.png)
![image](https://user-images.githubusercontent.com/37214323/142367073-f5939591-9d01-4218-95e5-7249565ba931.png)

**Comment by BeiQiaoT** [comment]
已处理
