### ISSUE TITLE
tabbar数字徽标badgeStyle传参没用

### ISSUE THREAD

**Issue by webjuzi** [umicro/uView2.0#336]
### 版本
2.0.27

### 转载链接
[http://undefined.null/](http://undefined.null)

### 重现步骤
文件路径:uView2.0/uni_modules/uview-ui/components/u-tabbar-item/u-tabbar-item.vue;
第27行   :customStyle="badgeStyle"   我进入u-badge组件发现没接收customStyle这个参数   我就把27行改为:style="badgeStyle"就正常了

### 期望的结果是什么？
customStyle可以正常用

### 实际的结果是什么？
customStyle传参无用

**Comment by yatoku** [comment]
这个组件经测试是没有问题的。
