### ISSUE TITLE
uni.requireNativePlugin is not a function

### ISSUE THREAD

**Issue by cxy-coder** [umicro/uView2.0#34]
在HBuilderX中编译是正常的也打开了微信开发者工具了，但是微信开发者工具中报错了
![image](https://user-images.githubusercontent.com/51732786/142372719-2c7016e3-7a34-4e4b-aed6-f6278871cafb.png)

_Originally posted by @cxy-coder in https://github.com/umicro/uView2.0/issues/9#issuecomment-972611662_

**Comment by tttao7** [comment]
请问是否最新的代码

**Comment by cxy-coder** [comment]
是的，今天准备在新的项目中尝试使用2.0的库

**Comment by micro-bean** [comment]
在入口js文件（main.js）增加代码覆盖uni报错：
`uni.requireNativePlugin = () => {};`

**Comment by social-uni** [comment]
遇到了相同的问题，应该是个popup这个组件有关

我在 vue.config.js中添加了 transpileDependencies: ['@dcloudio/uni-ui', 'uview-ui'] 之后可以了

**Comment by social-uni** [comment]
遇到了相同的问题，应该是个popup这个组件有关

我在 vue.config.js中添加了 transpileDependencies: ['@dcloudio/uni-ui', 'uview-ui'] 之后可以了

**Comment by lanyuzx** [comment]
vue3 中怎么解决

**Comment by alamhubb** [comment]
> vue3 中怎么解决

一样的吧，我现在用的就是vue3

**Comment by lanyuzx** [comment]
> > vue3 中怎么解决
> 
> 一样的吧，我现在用的就是vue3

使用vite脚手架创建的项目 没有 vue.config.js ,大佬报错几天了,求解决方案

**Comment by alamhubb** [comment]
> Reference in new is

vite的叫vite.config.js|ts
没有可以自己创建一个
