### ISSUE TITLE
时间格式化 ios出现NaN

### ISSUE THREAD

**Issue by yokochen222** [umicro/uView2.0#342]
### 这个功能解决了什么问题？
传入时间字符串 2022-02-10 10:34:33 经date('yyyy-mm') 转换后 出现0NaNNaN...

### 你期望的 API 是怎样的？
传入任意字符 格式化成指定样式

**Comment by meng-ling-feng** [comment]
貌似只能传时间戳哦，先把时间转化成时间戳

**Comment by xzd-inc** [comment]
非组件库问题
在Safari/Webkit中，new Date仅支持/作为分割符的字符串
例： 2022-02-10 10:34:33
需修改为为： 2022/02/10 10:34:33

**Comment by xzd-inc** [comment]
> ### 这个功能解决了什么问题？
> 传入时间字符串 2022-02-10 10:34:33 经date('yyyy-mm') 转换后 出现0NaNNaN...
> 
> ### 你期望的 API 是怎样的？
> 传入任意字符 格式化成指定样式
非组件库问题
在Safari/Webkit中，new Date仅支持/作为分割符的字符串
例： 2022-02-10 10:34:33
需修改为为： 2022/02/10 10:34:33
