### ISSUE TITLE
为什么修改项目名后，uView的代码提示就失效了

### ISSUE THREAD

**Issue by sherlockljx** [umicro/uView2.0#353]
### 版本
2.0.27

### 转载链接
[http://localhost:8080/](http://localhost:8080/)

### 重现步骤
新建项目test,npm导入配置uView，修改项目名（如uni-demo），uview代码提示失效

### 期望的结果是什么？
输入“<u”可以正常提示

### 实际的结果是什么？
代码提示失效

**Comment by yatoku** [comment]
重新构建项目索引。

**Comment by 569202812** [comment]
> 重新构建项目索引。

重新构建后也是不可以，需要使用uni_modules吗
