### ISSUE TITLE
u-input readonly 属性无效

### ISSUE THREAD

**Issue by jian22446688** [umicro/uView2.0#357]
### 版本
2.0.27

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/input.html)

### 重现步骤
直接用 readonly 

### 期望的结果是什么？
只读

### 实际的结果是什么？
不可输入

**Comment by meng-ling-feng** [comment]
亲测能用，你在哪个平台失效的

**Comment by yatoku** [comment]
这个属性只有在H5是存在的，后面会删掉的
