### ISSUE TITLE
Calendar 日历 日期与星期错位

### ISSUE THREAD

**Issue by SGodV** [umicro/uView2.0#36]
uview版本：2.0.3
平台：h5
问题：Calendar 日历组件 日期外层有padding导致与星期错位（猜测是不同平台box-sizing 的问题）

![image](https://user-images.githubusercontent.com/37214323/142378976-f1dd829a-3b53-4816-b491-35edb9ad8a40.png)
![image](https://user-images.githubusercontent.com/37214323/142379192-b11f62aa-bf7c-4eca-9984-d3bd3e26d9f1.png)

解决方式：删除padding值

![image](https://user-images.githubusercontent.com/37214323/142382176-65cb088f-2542-46ef-ba31-4920ebeaa5ae.png)
![image](https://user-images.githubusercontent.com/37214323/142382252-d80be213-7e0d-4926-a6c7-9f4300b95a4a.png)

**Comment by BeiQiaoT** [comment]
已处理
