### ISSUE TITLE
u-form-item组件中在添加了left-icon属性之后，报错leftIconStyle未定义

### ISSUE THREAD

**Issue by AK47-dadada** [umicro/uView2.0#360]
### 版本
2.0.27

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/form.html)

### 重现步骤
在给u-form-item的组件使用left-icon属性之后，报错leftIconStyle未定义
![image](https://user-images.githubusercontent.com/30396595/154384813-ce7ad6e9-84a2-4557-9c77-fd43a8dc54dc.png)

### 期望的结果是什么？
正常使用，不报错

### 实际的结果是什么？
报错，但是icon能展示

**Comment by yatoku** [comment]
已修复
