### ISSUE TITLE
customer-icon无法显示

### ISSUE THREAD

**Issue by hinet** [umicro/uView2.0#366]
### 版本
2.0.27

### 转载链接
[http://localhost:8080/](http://localhost:8080)

### 重现步骤
使用iconfont扩展图标库，按照文档定义custom-icon，添加custom-prefix="custom-icon"来使用图标无法显示，调试发现u-icon的class是u-icon__icon custom-icon-add而没有添加custom-icon类名造成的。

### 期望的结果是什么？
请官方修复

### 实际的结果是什么？
图标无法显示

**Comment by pengyinghao** [comment]
我也遇到了这个问题，请问你解决了没

**Comment by guixianleng** [comment]
> 请仔细查看文档https://www.uviewui.com/components/icon.html

1.x版本没问题，2.x使用同样的方式，图标显示不出来

**Comment by yatoku** [comment]
> > 请仔细查看文档https://www.uviewui.com/components/icon.html
> 
> 1.x版本没问题，2.x使用同样的方式，图标显示不出来

![image](https://user-images.githubusercontent.com/35695074/158922399-6ad0ea34-bccd-425b-bb4c-41c74b02466a.png)
