### ISSUE TITLE
修改uView内置配置方案时无效

### ISSUE THREAD

**Issue by a77uu** [umicro/uView2.0#369]
### 版本
2.0.27

### 转载链接
[http://localhost:8080/](http://localhost:8080)

### 重现步骤
需求是需要修改 Primary 主题色为 "#806452"
``` 
// main.js
...
import uView from 'uview-ui'
Vue.use(uView)
...
uni.$u.setConfig({
	color: {
		primary: '#806452'
	}
})
console.log(uni.$u.color)
```

配置过后，将首页添加的 button 组件的 type 值设为 primary ，样式无效。将 uni.$u.color 打印在控制台中发现其值已被修改。

```
{primary: '#806452', info: '#909399', default: '#909399', warning: '#f9ae3d', error: '#f56c6c', …}
```

### 期望的结果是什么？
所有的 primary 颜色改为 #806452

### 实际的结果是什么？
在 main.js 中 setConfig 后的颜色依旧是默认的 #3c9cff

**Comment by yatoku** [comment]
scss变量没改吧

**Comment by a77uu** [comment]
> scss变量没改吧

在 uni.scss 中修改后有效！

```
$u-primary: #806452;
```
