### ISSUE TITLE
编译成app，button点击事件失效

### ISSUE THREAD

**Issue by ig666** [umicro/uView2.0#375]
### 版本
2.0.27

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/button.html)

### 重现步骤
真机调试app，button点击事件偶尔编译后会失效

### 期望的结果是什么？
真机调试app，button点击事件正常触发

### 实际的结果是什么？
真机调试app，button点击事件不触发

---
Hbuilder版本 3.3.11.20220209

**Comment by yatoku** [comment]
uview的button组件自带了节流功能，是否与节流功能相关，或者是使用了`uni-simple-route`时，深度对象传参导致解析错误
