### ISSUE TITLE
nvue兼容问题 u--image

### ISSUE THREAD

**Issue by yueqiqi** [umicro/uView2.0#4]
### image组件在nvue中使用自定义loading和自定义error插槽无法显示

![WB{FNQC%J~} Y~`$M~X7@U](https://user-images.githubusercontent.com/50952334/141935799-e288ef1f-2787-4766-b75f-24c827e56243.png)
![07cd94e67bb564ac706b295f5da5a46](https://user-images.githubusercontent.com/50952334/141935690-0d1d17bf-6a07-4322-aa3a-f6ca73542afb.jpg)
![da4d6be8e7656ae9d68c076beee2272](https://user-images.githubusercontent.com/50952334/141935820-8b785e37-8cdb-45da-aca6-4f98d377c612.jpg)

**Comment by YanxinNet** [comment]
u-image组件不允许传递slot，仅用作图片展示使用，无其他功能和用途。
