### ISSUE TITLE
文档编写的变量名错误

### ISSUE THREAD

**Issue by Mcler520** [umicro/uView2.0#415]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/safeAreaInset.html)

### 重现步骤
https://github.com/umicro/uView2.0/blob/master/uni_modules/uview-ui/libs/css/vue.scss#L3
.u-safe-area-inset-*

文档中 u-safe-bottom

### 期望的结果是什么？
无

### 实际的结果是什么？
无

**Comment by yatoku** [comment]
文档中说这个`u-safe-bottom`是一个组件，uview2确实存在这个组件，好像没什么问题。
