### ISSUE TITLE
函数组件 render h函数渲染组件报错 Unknown custom element: <u-button>

### ISSUE THREAD

**Issue by rico0808** [umicro/uView2.0#419]
### 版本
2.0.29

### 转载链接
[http://localhost:8080/#/](http://localhost:8080/#/)

### 重现步骤
函数式组件 render h函数渲染组件提示 Unknown custom element: <u-button>

```
render(h) {
    return h('u-button', {}, '这是一个按钮');
}
```

报错信息
```
[Vue warn]: Unknown custom element: <u-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

### 期望的结果是什么？
可以正常渲染展示

### 实际的结果是什么？
未正常渲染展示

**Comment by yatoku** [comment]
`uniapp`中仅有`H5`环境下支持`render`函数，不知道你是不是因为这个原因导致的。但是都不推荐在`uniapp`中使用`render`函数。https://uniapp.dcloud.net.cn/tutorial/vue-api.html#%E9%80%89%E9%A1%B9
