### ISSUE TITLE
u-modal的文档问题

### ISSUE THREAD

**Issue by yixiancc** [umicro/uView2.0#42]
其中文档的Event事件中，确认的事件名为confirm，但是正确的调用方法是confrim，这可能拼错英语单词了
![image](https://user-images.githubusercontent.com/39053906/142554274-01f3de2d-69b1-4a39-8243-a0711ce6e679.png)
![image](https://user-images.githubusercontent.com/39053906/142554300-c5b1a637-8539-476d-a72a-c7bbd6ec71bf.png)

**Comment by MarkGor** [comment]
這個，新版本，好像修復了

**Comment by qinhir** [comment]
文档中存在比较多的英文拼写错误

**Comment by BeiQiaoT** [comment]
感谢，稍后处理
