### ISSUE TITLE
BUG也太多了吧，这种简单的两列选择器也能报错

### ISSUE THREAD

**Issue by TroyRay** [umicro/uView2.0#424]
### 版本
2.0.28

### 转载链接
[github.com](https://github.com/umicro/uView2.0/blob/master/uni_modules/uview-ui/components/u-picker/u-picker.vue)

### 重现步骤
简单的两列Picker都能报错。。。

### 期望的结果是什么？
正常选择

### 实际的结果是什么？
报Error

---
 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <UPicker> at uni_modules/uview-ui/components/u-picker/u-picker.vue

![image](https://user-images.githubusercontent.com/8155310/158536241-5a04cf38-884b-484c-a89e-61039a4a47b5.png)

**Comment by sysBlackFox** [comment]
你是怎么解决的啊，我是V2.0.31，我也遇到这个问题了，最后是用默认picker去写了吗

**Comment by FlyingTigerReally** [comment]
压根就没测试过

**Comment by cumt-robin** [comment]
哈哈，我也遇到了

**Comment by cumt-robin** [comment]
2.0.34版本依然存在这个问题

**Comment by Guwww** [comment]
抖音小程序 也出现同样报错，搞半天搞不定，直接删了，用uni-app的插件了。

**Comment by 1312003804** [comment]
截至目前 2.0.36还未解决
