### ISSUE TITLE
测试行为：非常抱歉，请删除这个issue。

### ISSUE THREAD

**Issue by ghost** [umicro/uView2.0#427]
非常抱歉，请删除这个issue。

**Comment by yatoku** [comment]
`onPreviewVideo`这个API是哪里来的？

**Comment by lxmob** [comment]
u-upload 组件中 => 源码 246 行

**Comment by lxmob** [comment]
> 

u-upload组件中onPreviewVideo方法

**Comment by yatoku** [comment]
> > 
> 
> u-upload组件中onPreviewVideo方法

源码看了一下好像是微信的API，估计只有微信小程序支持。所以没有添加到文档中

**Comment by lxmob** [comment]
sry, please remove this issue.
