### ISSUE TITLE
u-picker  confirm事件在微信小程序切换值与得到的值不正确

### ISSUE THREAD

**Issue by PZ-18664918826** [umicro/uView2.0#432]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/picker.html)

### 重现步骤
1.微信小程序
2.单列情况
3.切换值点击确定按钮 回调事件confirm的value不正确
4.h5 app倒是没问题

### 期望的结果是什么？
希望得到正确值

### 实际的结果是什么？
得到的值不正确

**Comment by monstereat** [comment]
我也遇到了，有时候可以有时候不行。

**Comment by yeluobaicaoku** [comment]
问题在于动画结束时才会改变具体的选中值，尤其是只有2-3个选项的时候，这个问题比较严重。

**Comment by monstereat** [comment]
> 问题在于动画结束时才会改变具体的选中值，尤其是只有2-3个选项的时候，这个问题比较严重。

只在微信2.21.1及以上有效  u-picker 加上这个属性，u-datetime-picker  也一样。
:immediateChange=“true"

**Comment by yeluobaicaoku** [comment]
> > 问题在于动画结束时才会改变具体的选中值，尤其是只有2-3个选项的时候，这个问题比较严重。
> 
> 只在微信2.21.1及以上有效 u-picker 加上这个属性，u-datetime-picker 也一样。 :immediateChange=“true"

无奈在于企业微信小程序目前最新仅到2.17.0，难道这个问题只能等待时间来解决了

**Comment by monstereat** [comment]
> > > 问题在于动画结束时才会改变具体的选中值，尤其是只有2-3个选项的时候，这个问题比较严重。
> > 
> > 
> > 只在微信2.21.1及以上有效 u-picker 加上这个属性，u-datetime-picker 也一样。 :immediateChange=“true"
> 
> 无奈在于企业微信小程序目前最新仅到2.17.0，难道这个问题只能等待时间来解决了

那你用原生的picker吧。我原来也提过issus，没发现这个属性，全切换成原生的picker了，想着这个bug提个pr，看到有这个属性。
