### ISSUE TITLE
checkbox 和 Radio 文档错误，或者是缺少Slot功能；

### ISSUE THREAD

**Issue by Mcler520** [umicro/uView2.0#433]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/checkbox.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2)

### 重现步骤
https://www.uviewui.com/components/checkbox.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2

<u-checkbox-group v-model="checked" placement="row">
	<u-checkbox activeColor="red">红色</u-checkbox>
	<u-checkbox activeColor="green">绿色</u-checkbox>
</u-checkbox-group>

u-checkbox 的源码中并未支持Slot 方式，如果支持请修复对应的Slot 文件。
https://github.com/umicro/uView2.0/blob/master/uni_modules/uview-ui/components/u-checkbox/u-checkbox.vue#L23

### 期望的结果是什么？
支持Slot 标签

### 实际的结果是什么？
文档中存在Slot语法，代码中却不支持

**Comment by yatoku** [comment]
文档错误

**Comment by yatoku** [comment]
已修改
