### ISSUE TITLE
全局tabbar使用方式还是和uview1一样的逻辑吗

### ISSUE THREAD

**Issue by jason-liang** [umicro/uView2.0#44]
文档里没有写，不知道如何是最佳实现方式

**Comment by gulullu** [comment]
加个中间凸起的特性吧。。

**Comment by orangepro11** [comment]
# 在H5端

在H5端uniapp的原生tabbar也是通过div渲染出来的，和自定义tabbar无本质区别，这个时候你可以把u-tabbar二次封装成一个组件，调用uni.hideTabbar()隐藏原生tabbar（你也可以直接不写原生tabbar），之后把tabbarList放到vuex里进行统一管理，setTabbarIndex也是通过vuex管理，之后在TabBar页面引入这个组件即可。

# 在非H5端
以小程序为例，如果通过上述方式使用在切换页面的时候会有闪烁问题。如果不希望闪烁则只能通过v-if去控制显示不同的页面（这个时候应该叫组件了，注意被tabbar控制的页面组件没有onReady，onShow，onHide这种页面生命周周期，就算你这个页面在pages,json里注册了也一样，只要是被import进来的统一作为组件处理）。
