### ISSUE TITLE
为什么日历组件u-calendar要求maxDate属性不能小于当前时间？

### ISSUE THREAD

**Issue by ouhsnaux** [umicro/uView2.0#441]
### 这个功能解决了什么问题？
日期单选时，如果最大日期小于当前时间会提示错误，并且日历组件无法使用。

### 你期望的 API 是怎样的？
不要限制最大日期不能小于当前时间

**Comment by yatoku** [comment]
你设置`maxDate`的同时设置了`minDate`了吗

**Comment by ouhsnaux** [comment]
源码判断的时候没考虑minDate

```vue
init() {
	// 校验maxDate，不能小于当前时间
	if (
		this.innerMaxDate &&
		new Date(this.innerMaxDate).getTime() <= Date.now()
	) {
		return uni.$u.error('maxDate不能小于当前时间')
	}
}
```

**Comment by yatoku** [comment]
> ### 这个功能解决了什么问题？
> 日期单选时，如果最大日期小于当前时间会提示错误，并且日历组件无法使用。
> 
> ### 你期望的 API 是怎样的？
> 不要限制最大日期不能小于当前时间



> 



> 源码判断的时候没考虑minDate
> 
> ```
> init() {
> 	// 校验maxDate，不能小于当前时间
> 	if (
> 		this.innerMaxDate &&
> 		new Date(this.innerMaxDate).getTime() <= Date.now()
> 	) {
> 		return uni.$u.error('maxDate不能小于当前时间')
> 	}
> }
> ```

因为还要考虑`defaultDate`,假如你只是设置了`maxDate`和`minDate`。但是defaultDate又不在其中的话，就会有问题。那样还需要校验`defaultDate`的合法性

**Comment by yatoku** [comment]
> 源码判断的时候没考虑minDate
> 
> ```
> init() {
> 	// 校验maxDate，不能小于当前时间
> 	if (
> 		this.innerMaxDate &&
> 		new Date(this.innerMaxDate).getTime() <= Date.now()
> 	) {
> 		return uni.$u.error('maxDate不能小于当前时间')
> 	}
> }
> ```

因为目前在没有设置`defaultDate`的情况下，默认是当前时间
