### ISSUE TITLE
引用的组件如何通过覆盖class重写样式

### ISSUE THREAD

**Issue by FeSeason** [umicro/uView2.0#442]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/slider.html)

### 重现步骤
使用的一些组件在样式上不是特别满足需求，需要改造但是覆盖class 的写法上看不生效 不知道为啥？

### 期望的结果是什么？
样式生效

### 实际的结果是什么？
不生效

**Comment by yatoku** [comment]
https://www.kancloud.cn/uview/uview-ui_v2/2587980

**Comment by FeSeason** [comment]
> https://www.kancloud.cn/uview/uview-ui_v2/2587980

在app内，解决了 用 /deep/
