### ISSUE TITLE
picker 在表单中不同选项复用时会保留上次索引

### ISSUE THREAD

**Issue by FeSeason** [umicro/uView2.0#444]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/picker.html)

### 重现步骤
多个数据源对应一个 picker 时  在切换不同的表单字段，传入 picker数据时会保留上一次的索引，有可能有的picker数据索引不存在

### 期望的结果是什么？
提供一个重置索引的方法？

### 实际的结果是什么？
索引可控

**Comment by yatoku** [comment]
动态设置`defaultIndex`试试
