### ISSUE TITLE
从1.x升级到2.0.29后，u-icon组件就会出现两个相同图标的情况，这种情况要怎么解决呢？

### ISSUE THREAD

**Issue by Seifon** [umicro/uView2.0#445]
### 重现步骤
从1.x升级到2.0.29后，u-icon组件就会出现两个相同图标的情况，这种情况要怎么解决呢？

[![qUN7xf.png](https://s1.ax1x.com/2022/03/26/qUN7xf.png)](https://imgtu.com/i/qUN7xf)

**Comment by yatoku** [comment]
可以提同一个最小可复现示例吗
