### ISSUE TITLE
uList在vue页面不能触发页面下拉刷新

### ISSUE THREAD

**Issue by heygays** [umicro/uView2.0#450]
### 版本
2.0.29

### 转载链接
[http://www.uviewui.com/](http://www.uviewui.com/)

### 重现步骤
非NVUE页面，page.json里面配置页面 "enablePullDownRefresh": true ，然后在页面使用了ulist,ulist-item后，无法触发下拉刷新

### 期望的结果是什么？
可以触发下拉刷新

### 实际的结果是什么？
未触发下拉刷新

**Comment by yatoku** [comment]
因为在vue页面`u-list`使用的是`scroll-view`所以下拉的滚动事件可能被`scroll-view`捕获了。你可以在`u-list`前面加个别的元素再试试

**Comment by jianshen-weo** [comment]
> 因为在vue页面`u-list`使用的是`scroll-view`所以下拉的滚动事件可能被`scroll-view`捕获了。你可以在`u-list`前面加个别的元素再试试

请问怎么在前面加元素试？？

**Comment by yatoku** [comment]
比如说加个搜索框什么的，然后固定`scroll-view`的高度，下拉时手指在非滚动区域上
