### ISSUE TITLE
upload组件previewImage字段判断位置错误

### ISSUE THREAD

**Issue by EarhartZhao** [umicro/uView2.0#454]
### 版本
2.0.29

### 转载链接
[github.com](https://github.com/umicro/uView2.0/blob/master/uni_modules/uview-ui/components/u-upload/u-upload.vue)

### 重现步骤
upload组件设置previewImage属性，upload组件都会隐藏

### 期望的结果是什么？
upload组件设置previewImage属性，upload组件不会隐藏，预览图隐藏

### 实际的结果是什么？
upload组件设置previewImage属性，upload组件都会隐藏

**Comment by yatoku** [comment]
unload是什么？

**Comment by EarhartZhao** [comment]
> unload是什么？

upload

**Comment by yatoku** [comment]
如果你没有限制上传数量的话，上传的组件还是会显示的

**Comment by yatoku** [comment]
看源码明白了，但是你的描述有问题

**Comment by EarhartZhao** [comment]
> 

下次一定 😂
