### ISSUE TITLE
switch组件代码错误，不兼容rpx

### ISSUE THREAD

**Issue by fainc** [umicro/uView2.0#455]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/switch.html)

### 重现步骤
全局设置单位rpx switch组件样式异常，错误代码：style.transform = `translateX(${this.value === this.activeValue ? -this.space : -this.size}px)`；translateX计算错误

### 期望的结果是什么？
修复兼容rpx

### 实际的结果是什么？
应兼容px和rpx单位

---
错误代码：style.transform = `translateX(${this.value === this.activeValue ? -this.space : -this.size}px)`，应兼容px和rpx单位

**Comment by yatoku** [comment]
已修复
