### ISSUE TITLE
NoticeBar 滚动通知 ，多条通知时候存在问题。

### ISSUE THREAD

**Issue by oktool** [umicro/uView2.0#458]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/noticeBar.html)

### 重现步骤
text	显示的内容，direction为column时要求为数组， 为row时要求为字符串。Array | String
url	跳转的页面路径	String
当text为数组时候，点击所有的通知（text数组里的值），都跳转到同一个地址（URL）。

### 期望的结果是什么？
点击不同的通知，应该跳转到对应的网址（不同的URL）。

### 实际的结果是什么？
点击不同的通知，都跳转到同一个URL。

---
建议text的值可以是对象形式的数组。比如  text = [ { id:1, url="xxx"}, { id:2, url="xxx2"}  ]

**Comment by oktool** [comment]
通知栏能显示_**多条通知**_。并且能跳转到**对应的**通知详情页。

**Comment by yatoku** [comment]
以下情况时，`click`事件是会携带点击下标的index的。可以自行操作跳转不需要使用url
```js
v-if="direction === 'column' || (direction === 'row' && step)"
```
