### ISSUE TITLE
Button组件官方文档用例错误

### ISSUE THREAD

**Issue by doraemon00** [umicro/uView2.0#459]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/button.html)

### 重现步骤
官方示例中的 通过loading值设置是否开启加载图标，loadingText设置加载中文字

`<u-button type="primary" loading="true" loadingText="加载中"></u-button>`

loading 传入的值需为Boolean,文档中为String

### 期望的结果是什么？
`<u-button type="primary" :loading="true" loadingText="加载中"></u-button>`

### 实际的结果是什么？
`<u-button type="primary" loading="true" loadingText="加载中"></u-button>
`

**Comment by BeiQiaoT** [comment]
已处理
