### ISSUE TITLE
`u-cell` 文档介绍与源码不一致

### ISSUE THREAD

**Issue by jiangmaniu** [umicro/uView2.0#46]
![image](https://user-images.githubusercontent.com/50100681/142578805-2208fd64-aaf3-4994-9a69-fd1c248b5558.png)

文档中使用的是默认插槽，但 `u-cell` 没有默认插槽，只有与之类似的 `value` 插槽

**Comment by yatoku** [comment]
你这截图里的不是默认插槽啊，使用的不是`title`和`value`插槽吗？
