### ISSUE TITLE
列表组件滚动有问题

### ISSUE THREAD

**Issue by augushong** [umicro/uView2.0#469]
### 版本
2.0.29

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/list.html)

### 重现步骤
https://www.uviewui.com/components/list.html

这个滚动组件有问题，中间会卡主，官网示例也是有问题的，下次更新能改出来吗
示例中，滚动到17个左右，滚动条在滚动，但是内容已经卡住了

### 期望的结果是什么？
正常滚动

### 实际的结果是什么？
滚动条在滚动，但是内容抖动卡主

**Comment by white-007** [comment]
nvue下没问题，H5上确实有中间会卡住的问题，小程序没测

**Comment by yatoku** [comment]
#149 在这里面又解决方法
