### ISSUE TITLE
upload 组件手动调起选择图片

### ISSUE THREAD

**Issue by 1014156094** [umicro/uView2.0#477]
### 这个功能解决了什么问题？
用自己的按钮触发上传

### 你期望的 API 是怎样的？
upload 组件手动调起 upload 组件选择图片，现在有临时解决方法么？

**Comment by yatoku** [comment]
https://uniapp.dcloud.io/api/media/image.html#chooseimage

**Comment by yatoku** [comment]
或者使用`refs`例如`this.$refs.upload.chooseFile()`
