### ISSUE TITLE
u-checkbox-group双向绑定有问题

### ISSUE THREAD

**Issue by yangle594** [umicro/uView2.0#49]
![1637375022(1)](https://user-images.githubusercontent.com/65636470/142711242-d7bd9702-2b38-44b9-a1a3-e031c7dd72da.png)
u-checkbox-group双向绑定的数组,对数组进行删除子项选中状态不更新，一直处与勾选状态

**Comment by BeiQiaoT** [comment]
> ![1637375022(1)](https://user-images.githubusercontent.com/65636470/142711242-d7bd9702-2b38-44b9-a1a3-e031c7dd72da.png) u-checkbox-组事件绑定的数组，对数组进行删除子项选中状态不更新，一直处于与勾选状态

修改数组内的对象，不是响应式的吧，尝试用vue.set

**Comment by huangsy244** [comment]
关闭了？还是有问题呀

**Comment by definedw** [comment]
看源码好像是$emit('input', !this.value)在多层组件无法绑定父组件属性引发的问题

**Comment by wfs498121294** [comment]
还是有问题

**Comment by zhaoyuanmeng** [comment]
咋解决的阿
