### ISSUE TITLE
nvue，u--image @load="imageLoad"，event  undefined  

### ISSUE THREAD

**Issue by lilinjian2001** [umicro/uView2.0#497]
### 版本
2.0.30

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/image.html)

### 重现步骤
```
<template>
	<view>
		<u--image :src="src" radius="5 5 0 0" width="100" height="100" @load="imageLoad" ></u--image>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				src: "https://user-images.githubusercontent.com/31834927/162876229-95f61e8c-2032-4f4e-9f04-9dd455b3a94b.jpg"
			};
		},
		methods: {
			imageLoad(event) {
				console.log('event', event);
			}
		}
	}
</script>
```
APP Android真机调试

![QQ截图20220412114335](https://user-images.githubusercontent.com/31834927/162876045-0711414f-a9fb-4f0f-8c02-87b4f181ed15.png)

### 期望的结果是什么？
获取到事件对象event.detail = {height:'图片高度px', width:'图片宽度px'}

### 实际的结果是什么？
event undefined

**Comment by yatoku** [comment]
这个事件只是通知图片加载完成这么一个事情而已

**Comment by lilinjian2001** [comment]
既然这个组件是基于 uniapp image的加强版，在uniapp已经支持。所以期望与uniapp保持一致
https://uniapp.dcloud.io/component/image.html
