### ISSUE TITLE
uview2.0 组件的style 不加scoped 全局css 影响 太大了

### ISSUE THREAD

**Issue by taoaiyi1108** [umicro/uView2.0#50]
uview2.0 组件的style 不加scoped 全局css 影响 太大了

-- uview-2.0 
![image](https://user-images.githubusercontent.com/29810247/142789840-a5c02b1a-fa11-42ac-944c-78641cd4eb6f.png)

-- uview-1.0 
![image](https://user-images.githubusercontent.com/29810247/142789884-d8ac3822-fbc4-4eb2-863f-e9dc34b3ccf3.png)

-- uview2.0 项目使用
![image](https://user-images.githubusercontent.com/29810247/142789922-4ca382a9-68a1-4f45-8c17-580e704c8852.png)

**Comment by xyftx2010** [comment]
+1
