### ISSUE TITLE
使用uview 在微信小程序开发者工具中提示组件找不到

### ISSUE THREAD

**Issue by github-ZH-cn** [umicro/uView2.0#502]
### 版本
2.0.30

### 转载链接
[http://192.168.43.181:8080/](http://192.168.43.181:8080/)

### 重现步骤
使用npm构建uview打开小程序提示[ pages/index/index.json 文件内容错误] pages/index/index.json: ["usingComponents"]["u-icon"] 未找到,有解决办法吗

### 期望的结果是什么？
得到解决

### 实际的结果是什么？
希望可以解决这个问题

**Comment by Kaiter-Plus** [comment]
这个问题大概率又 IDE 引起，可以通过重启软件（uniapp 和 微信开发者工具）解决

**Comment by github-ZH-cn** [comment]
它通过下载的方式已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umicro/uView2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umicro/uView2.0] 使用uview 在微信小程序开发者工具中提示组件找不到 (Issue #502)





 
这个问题大概率又 IDE 引起，可以通过重启软件（uniapp 和 微信开发者工具）解决
