### ISSUE TITLE
官网例子 代码错误

### ISSUE THREAD

**Issue by ZZC1206** [umicro/uView2.0#513]
### 版本
2.0.31

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/input.html)

### 重现步骤
 <u--input
    placeholder="请输入内容"
    border="surround"
    v-model="value"
    @change="change"
  ></u--input>
报错：Cannot find module 'uview-ui/components/u--input/u--input.vue'
1. 排查组件名称拼写是否正确
2. 排查组件是否符合 easycom 规范，文档：https://uniapp.dcloud.net.cn/collocation/pages?id=easycom
3. 若组件不符合 easycom 规范，需手动引入，并在 components 中注册该组件；

标签要修改成 这个 u-input 例子 多了个 '-'

### 期望的结果是什么？
修改好官网例子

### 实际的结果是什么？
修改好官网例子

**Comment by yatoku** [comment]
`u--input`这个组件是存在的，不过`u--`的组件仅需要在`app-nvue`的情况下使用，支付宝小程序上使用会出现问题

**Comment by ZZC1206** [comment]
谢谢哈~我知道问题在哪里了...npm 安装 默认版本是 [1.8.6]，官网的例子需要 2.0 版本
