### ISSUE TITLE
uniapp已经全面支持vue3了，今天vue3大普及，什么时候支持vue3

### ISSUE THREAD

**Issue by xiaobailong007** [umicro/uView2.0#524]
### 这个功能解决了什么问题？
uniapp已经全面支持vue3了，今天vue3大普及，什么时候支持vue3

### 你期望的 API 是怎样的？
从1月份等到快5月份了，希望支持vue3

**Comment by ifzm** [comment]
mark

**Comment by lentg** [comment]
mark

**Comment by yatoku** [comment]
uview1.x和uview2.x都不会支持，后续可能会有uview3的计划会支持
