### ISSUE TITLE
uni-app 打包的时候报错

### ISSUE THREAD

**Issue by liutengfei1991** [umicro/uView2.0#526]
### 版本
2.0.31

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/npmSetting.html#_5-cli%E6%A8%A1%E5%BC%8F%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE)

### 重现步骤
小程序，没有重现链接，uview2.0 构建报错

### 期望的结果是什么？
不报错

### 实际的结果是什么？
报错

---
Module parse failed: Unexpected token (40:49)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader/index.js
You may need an additional loader to handle the result of these loaders.
| // 看到此报错，是因为没有配置vue.config.js的【transpileDependencies】，详见：https://www.uviewui.com/components/npmSetting.html#_5-cli模式额外配置
| const pleaseSetTranspileDependencies = {},
>       babelTest = pleaseSetTranspileDependencies?.test; // 引入全局mixin
|
| const $u = {

 @ ./src/main.js 18:38-57
 @ multi ./src/main.js

 ERROR  Build failed with errors.

**Comment by liutengfei1991** [comment]
node 版本16就行，12就可以

**Comment by yatoku** [comment]
那可能就是nodejs版本的问题 你自己改一下版本就好了

**Comment by liutengfei1991** [comment]
之前是"build:h5-test": "cross-env NODE_ENV=test UNI_PLATFORM=h5 vue-cli-service uni-build",

把test改成了test1，就可以了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umicro/uView2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umicro/uView2.0] uni-app 打包的时候报错 (Issue #526)





 
那可能就是nodejs版本的问题 你自己改一下版本就好了
