### ISSUE TITLE
uniapp,vue3版本支持使用uview

### ISSUE THREAD

**Issue by qiyx2019** [umicro/uView2.0#527]
### 这个功能解决了什么问题？
能够在vue3下正常运行uview

### 你期望的 API 是怎样的？
修改install方法如下:
 const install = (Vue) => {
    try {
        const version = Number(Vue.version.split('.')[0])
        if (version < 3) {
            // #ifndef APP-NVUE
            Vue.prototype.$u = $u
            Vue.mixin(mixin)
            // #endif
        } else {
            // #ifndef APP-NVUE
            // 只有vue，挂载到Vue.prototype才有意义，因为nvue中全局Vue.prototype和Vue.mixin是无效的
            Vue.config.globalProperties.$u = $u
            Vue.mixin(mixin)
            // #endif
        }
    } catch (e) {
        console.log
    }
}

**Comment by yatoku** [comment]
不支持

**Comment by xbmlz** [comment]
可以使用 vk-uview-ui，同时支持vue2.x和vue3.x， 
https://vkuviewdoc.fsq.pub/

或者现成的框架，vite3.x + vue3 + pinia + vk-uview-ui + ucharts
https://github.com/venable-dev/venable-uniapp
