### ISSUE TITLE
uview2.0没有找到按需引用，导致打包到微信小程序的包很大，运行错误

### ISSUE THREAD

**Issue by xsdream** [umicro/uView2.0#528]
### 版本
2.0.31

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/install.html)

### 重现步骤
import uView from '@/uni_modules/uview-ui'
Vue.use(uView)

### 期望的结果是什么？
提供按需引入

### 实际的结果是什么？
install了所有包

**Comment by yatoku** [comment]
请自己看uniapp easycom的介绍
