### ISSUE TITLE
组件在支付宝小程序无法使用

### ISSUE THREAD

**Issue by helibin** [umicro/uView2.0#529]
### 版本
2.0.28

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/input.html)

### 重现步骤
编译到支付宝，u--开头的组件全部报错，比如u--input, u--text等

### 期望的结果是什么？
跨平台抹平差异

### 实际的结果是什么？
微信小程序可以使用，支付宝小程序不能，其他平台小程序未测试

**Comment by yatoku** [comment]
可以看看为什么要有`u--`组件，只有在`app-nvue`的环境下才需要使用`u--`组件
