### ISSUE TITLE
uView UI官方13群的管理员【珍惜眼前人】为什么踢人？

### ISSUE THREAD

**Issue by xsdream** [umicro/uView2.0#531]
### 版本
2.0.31

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/changelog.html)

### 重现步骤
作为官方群，本着解决问题为主，为什么管理员随意踢人。

### 期望的结果是什么？
给一个合理的解释，不要删issues

### 实际的结果是什么？
给一个合理的解释，不要删issues

**Comment by xsdream** [comment]
![image](https://user-images.githubusercontent.com/31870384/165667106-02568932-e5d1-4d00-9642-36c43c36a523.png)

**Comment by xsdream** [comment]
事情的缘由是我在群里请教一个人问题，然后这个人冒出来一句【显得好小白】，我就和他理论，我说他作为管理员不能这样说话，然后过了几分钟，他就把我踢了！！！

**Comment by xsdream** [comment]
事情的缘由是我在群里请教一个人问题，然后这个人冒出来一句【显得好小白】，我就和他理论，我说他作为管理员不能这样说话，然后过了几分钟，他就把我踢了！！！

**Comment by yatoku** [comment]
因为你太二杯了

**Comment by xsdream** [comment]
@yatoku 因为我是你die

**Comment by hblz** [comment]
@xsdream  群里面的管理员 没有素质 我提问 不回答 还私聊 辱骂人，uview 有这些素质人 堪忧啊

**Comment by hblz** [comment]
![1655260914777](https://user-images.githubusercontent.com/13432481/173726859-ce0840c9-59b5-4c81-90af-150da5221d40.jpg)

**Comment by xsdream** [comment]
@hblz 这个库的管理员觉得自己老牛皮了，优越感十足
