### ISSUE TITLE
uView UI官方13群的管理员【珍惜眼前人】为什么踢人？

### ISSUE THREAD

**Issue by xsdream** [umicro/uView2.0#532]
### 版本
2.0.31

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/changelog.html)

### 重现步骤
https://www.uviewui.com/components/changelog.html

### 期望的结果是什么？
uView UI官方13群的管理员【珍惜眼前人】为什么踢人？

### 实际的结果是什么？
uView UI官方13群的管理员【珍惜眼前人】为什么踢人？

**Comment by xsdream** [comment]
![image](https://user-images.githubusercontent.com/31870384/165667290-380c9ad5-8e93-49ac-bf15-a86ef84278a5.png)

**Comment by xsdream** [comment]
事情的缘由是我在群里请教一个人问题，然后这个人冒出来一句【显得好小白】，我就和他理论，我说他作为管理员不能这样说话，然后过了几分钟，他就把我踢了！！！

**Comment by xsdream** [comment]
事情的缘由是我在群里请教一个人问题，然后这个人冒出来一句【显得好小白】，我就和他理论，我说他作为管理员不能这样说话，然后过了几分钟，他就把我踢了！！！

**Comment by xsdream** [comment]
事情的缘由是我在群里请教一个人问题，然后这个人冒出来一句【显得好小白】，我就和他理论，我说他作为管理员不能这样说话，然后过了几分钟，他就把我踢了！！！

**Comment by yatoku** [comment]
因为你太二杯了

**Comment by xsdream** [comment]
@yatoku 因为我是你die

**Comment by yatoku** [comment]
我不需要你这种傻逼儿子，别叫了

**Comment by xsdream** [comment]
@yatoku 撇开一切，我都是你爹，当年就应该把你she在墙上

**Comment by yatoku** [comment]
抛开一切不谈是吧，真的是没脑子

**Comment by yatoku** [comment]
狗叫让你自己很享受吗

**Comment by xsdream** [comment]
@yatoku 你的嘴舔了马桶？

**Comment by xsdream** [comment]
@yatoku 你脑子里的水是为了浇灌你心里的b树吗？

**Comment by xsdream** [comment]
@yatoku 你能秒射，为什么不能秒回？TMD

**Comment by ja37l** [comment]
这素质也能当管理员哦？

**Comment by yatoku** [comment]
这素质也能做人？不remake

**Comment by ja37l** [comment]
> 这素质也能做人？不remake

@yatoku 说你了么？去你妈逼里找存在感

**Comment by hblz** [comment]
@xsdream @ja37l  UVIEW 有这群没素质的开发者，堪忧，还私聊骂，这现象太普遍了
![1655260914777](https://user-images.githubusercontent.com/13432481/173727747-8cb259e4-5256-4962-9df2-205014abd7f9.jpg)
人
