### ISSUE TITLE
可以看看为什么要有`u--`组件，只有在`app-nvue`的环境下才需要使用`u--`组件

### ISSUE THREAD

**Issue by helibin** [umicro/uView2.0#533]
可以看看为什么要有`u--`组件，只有在`app-nvue`的环境下才需要使用`u--`组件

_Originally posted by @yatoku in https://github.com/umicro/uView2.0/issues/529#issuecomment-1111692425_

相关说明是有提前看的，改回u-组件，支付宝也编译失败，应该是组件里带有u--组件，我目前的解决方案是把u--组件全改成了un-组件，勉强可用，官方可以考虑去掉u--，这个坑实在不小哦

**Comment by yatoku** [comment]
就算去掉`u--`也必然需要一个别的名字替代，其实这个`u--`的问题也是支付宝小程序转译产生的，事先并不能预想到这种情况，如果使用`un-`就不能满足在pages.json中使用`easycom`的统一注册
