### ISSUE TITLE
建议：DatetimePicker增加秒数选择

### ISSUE THREAD

**Issue by RedStarGroup** [umicro/uView2.0#534]
### 这个功能解决了什么问题？
我们是v1版本的用户，最近想将项目升级到v2，但是发现时间选择组件无法选择秒数了，个人觉得秒数选择实际上还是有很多使用场景的，比如我司项目属于智能设备实时、历史状态的查询业务，就需要选择精确到秒的查询。这点v1版本就没问题，还是希望官方能够加上

### 你期望的 API 是怎样的？
DatetimePicker增加time和date-time模式下的秒数选择

**Comment by yatoku** [comment]
不兼容升级，别升

**Comment by androidxu** [comment]
还没有官方的扩展组件好用，我真的服了这玩意
