### ISSUE TITLE
u-icon有bug

### ISSUE THREAD

**Issue by hdtopku** [umicro/uView2.0#539]
### 版本
2.0.31

### 转载链接
[http://localhost/](http://localhost)

### 重现步骤
https://at.alicdn.com/t/font_2138434_mpdoy34mah.css?spm=a313x.7781069.1998910419.51&file=font_2138434_mpdoy34mah.css
上面是我用的iconfont.css，
完整以下按照教程做的：
https://www.uviewui.com/guide/customIcon.html

### 期望的结果是什么？
```
<u-icon name="fenxiang" custom-prefix="custom-icon" size="30" color="#888888"></u-icon>
```
显示出（向下箭头+fenxiang）
![image](https://user-images.githubusercontent.com/14859466/166135051-89e23d4c-8615-466a-89b1-058dbddf7008.png)

↓fenxiang

### 实际的结果是什么？
未按理想结果显示

---
gitee有人也提出了此bug
https://gitee.com/umicro/uView2.0#note_9890540

u-icon 有bug，引用了iconfont，根据代码里的逻辑 classes.push(this.customPrefix + '-' + this.name) 无法生成可以符合iconfont 的类名，且会把图标的名称作为text渲染出来。

**Comment by hdtopku** [comment]
<u-icon name="share" custom-prefix="custom-icon" size="30" color="#888888"></u-icon>
出现两个图标
![image](https://user-images.githubusercontent.com/14859466/166135109-69be685b-0240-47b4-ba92-f211ca4ee55f.png)

<u-icon name="share1" custom-prefix="custom-icon" size="30" color="#888888"></u-icon>
出现如下
![image](https://user-images.githubusercontent.com/14859466/166135123-4a5d814b-1df6-4bbf-86e8-4fa8f8805907.png)

**Comment by hdtopku** [comment]
按照教程，项目设置和下载到本地，试了很多次，还是有bug，以下也放在App.vue样式的首行
```
@import './static/iconfont.css';
```
![image](https://user-images.githubusercontent.com/14859466/166135218-81197ad5-15b8-4409-82a2-f3ff63ca9801.png)

**Comment by yatoku** [comment]
这样改下
```js
// 通过图标名，查找对应的图标
icon() {
    // 如果内置的图标中找不到对应的图标，就直接返回name值，因为用户可能传入的是unicode代码
    if(this.customPrefix == 'custom-icon'){
	    return ''
    }
    return icons['uicon-' + this.name] || this.name
}
```

**Comment by hdtopku** [comment]
> 这样改下
> 
> ```js
> // 通过图标名，查找对应的图标
> icon() {
>     // 如果内置的图标中找不到对应的图标，就直接返回name值，因为用户可能传入的是unicode代码
>     if(this.customPrefix == 'custom-icon'){
> 	    return ''
>     }
>     return icons['uicon-' + this.name] || this.name
> }
> ```
是这个原因吗？我选的是font class，不是unicode

![image](https://user-images.githubusercontent.com/14859466/166138025-cb25ca35-ce60-4172-9eb4-d0f4cefabb94.png)

**Comment by yatoku** [comment]
> > 这样改下
> > ```js
> > // 通过图标名，查找对应的图标
> > icon() {
> >     // 如果内置的图标中找不到对应的图标，就直接返回name值，因为用户可能传入的是unicode代码
> >     if(this.customPrefix == 'custom-icon'){
> > 	    return ''
> >     }
> >     return icons['uicon-' + this.name] || this.name
> > }
> > ```
> 
> 是这个原因吗？我选的是font class，不是unicode
> 
> ![image](https://user-images.githubusercontent.com/14859466/166138025-cb25ca35-ce60-4172-9eb4-d0f4cefabb94.png)

因为要兼容`nvue`只有`unicode`这种方式，如果你不需要兼容`nvue`的话，就去掉这个`name`就好了

**Comment by hdtopku** [comment]
bug依然存在，请勿关闭此issue
## 按要求修改代码
![image](https://user-images.githubusercontent.com/14859466/167303374-ebcfd506-8d8d-427d-a7ed-9db44ca1e8d7.png)
## 使用
```
<u-icon name="plus-square" custom-prefix="custom-icon" color="#2979ff" size="66"></u-icon>
<u-icon name="WeChat" custom-prefix="custom-icon" color="#2979ff" size="66"></u-icon>
```
## 结果
![image](https://user-images.githubusercontent.com/14859466/167303591-42f2a558-0e6f-4939-9030-c6146c94a8dd.png)

## 我的icon矢量图标
![image](https://user-images.githubusercontent.com/14859466/167303623-77a8020c-7179-4b5a-9603-3886ad8cb6a3.png)

**Comment by hdtopku** [comment]
## 图标串了
@yatoku @yuanjianhua @zw3639 @chenli1989
