### ISSUE TITLE
Picker组件cancelText及confirmText无法使用的问题

### ISSUE THREAD

**Issue by su797** [umicro/uView2.0#55]
版本:2.X
组件路径:uview-ui/components/u-picker.vue
u-toolbar中没有添加
`:cancelText="cancelText"
:confirmText="confirmText"`
属性，导致设置cancelText和confirmText时无法更改对应文字
![image](https://user-images.githubusercontent.com/40026391/142834501-a919e12f-d874-4076-b737-f0be945dc0fb.png)

改为
`
<u-toolbar
				v-if="showToolbar"
				:cancelColor="cancelColor"
				:confirmColor="confirmColor"
				:cancelText="cancelText"
				:confirmText="confirmText"
				:title="title"
				@cancel="cancel"
				@confirm="confirm"
			></u-toolbar>
`
后，可正常设置
![image](https://user-images.githubusercontent.com/40026391/142834689-c4e6d63b-06b4-41d8-9607-757c3bf0bcf5.png)

**Comment by BeiQiaoT** [comment]
已经修复，拉取最新的代码
