### ISSUE TITLE
微信小程序打包，占用体积过大（1.62mb）

### ISSUE THREAD

**Issue by SilvesterLi** [umicro/uView2.0#588]
我看官网上写着最多占用500k，但是我压缩了，发行了，依旧占了1.62MB，是怎么回事
![image](https://user-images.githubusercontent.com/32910614/170852126-c2df34e2-9121-4886-826b-9305f57e07ac.png)

**Comment by tanminghang** [comment]
+1

**Comment by tanminghang** [comment]
不要用npm的方式引入，下载下来放进去就行了
![image](https://user-images.githubusercontent.com/83405146/172628664-0c370c05-97e1-4c03-af3f-a79f08ba6571.png)

**Comment by SilvesterLi** [comment]
我想我已经关闭了这个issue,
造成的原因是我用了全局css，uview官网也提示用户少用全局css。

**Comment by xuanxuan321** [comment]
请问这个包的体积是通过什么软件来分析的呢
