### ISSUE TITLE
datetimePicker设置了最大限制的选择跨月的问题

### ISSUE THREAD

**Issue by wangslsl** [umicro/uView2.0#597]
如题
https://www.uviewui.com/components/datetimePicker.html
<u-datetime-picker
  ref="datetimePicker"
  :show="dateShow"
  v-model="shrqNum"
  :minDate="minDate"  // 最小值为 2022-05-31
  :maxDate="maxDate" // 最大值为 2022-06-06
  mode="date"
  :formatter="formatter"
  @cancel="() => {this.dateShow = false}"
  @confirm="handleConfirm"
></u-datetime-picker>
默认是选中的 5月31日 月份切换到6月会返回已选中的日期为 2022-06-06 即maxDate , 但是UI界面却自动日期是 01 
如图
![1bdd4a01b6bf783def8e3bf7d6f49f5](https://user-images.githubusercontent.com/39260722/171215568-04f8f52c-4815-4df0-87ce-659868316d27.png)
01日并不是选中的样式. 06日是选中的样式
问题代码为:

![image](https://user-images.githubusercontent.com/39260722/171215874-948c8bef-0e8a-4058-9147-011c8b8b6551.png)

期望结果为 UI和返回的值一致  最好是自动到下一个月的1号自动选中

**Comment by TestRobot10086** [comment]
同样的问题，有没有解决办法的？

**Comment by sRect** [comment]
> https://github.com/umicro/uView2.0/issues/1109#issuecomment-2477820553

- u-datetime-picker.vue
```diff
// 更新索引
updateIndexs(value) {
...
- this.innerDefaultIndex = indexs;
+ this.$nextTick(() => {
+   this.innerDefaultIndex = indexs;
+ })
}

```
