### ISSUE TITLE
在nvue页面中使用<u--form 打离线包报错

### ISSUE THREAD

**Issue by hblz** [umicro/uView2.0#613]
### 版本
2.0.31

### 转载链接
[new-issue.uviewui.com/](https://new-issue.uviewui.com/?repo=umicro/uView2.0)

### 重现步骤
下载hbuilderx 3.4.15版本；进行对uView 2.0 官方demo进行离线打包；

### 期望的结果是什么？
能正常打包

### 实际的结果是什么？
无法正常打包

---
在群里问 竟然有私聊 骂人。。。这样的人员还配在uview群吗

**Comment by hblz** [comment]
@[http://125.77.202.162:24124/ff_user/AlarmImg/2022/06/15/041BCD893C0448A399A9C1374169E253.jpg](url) 请自己看连接

**Comment by hblz** [comment]
![1655260914777](https://user-images.githubusercontent.com/13432481/173726916-080cb127-332c-4ddb-9a6c-5eb13c31e837.jpg)

**Comment by BeiQiaoT** [comment]
离线打包应该是可以的，能提供更多信息吗？有可能是hbx的问题
我不认识你说的这位管理

**Comment by hblz** [comment]
@574770458 你骂人还有理了 你的素质垃圾到极品，至少我脾气冲动点（当时着急打包，又打不出来），但不至于辱骂他人。至于你，还愤青？？是你父母没教你怎么做人吧。打着愤青的名义骂人？不要丢愤青的脸。
PS :对uview带来困扰我道歉（已删除该删除的片段）；对你这个没素质的东西，不要打着愤青的名义，来光明正大辱骂他人？劝你做个人。

**Comment by 574770458** [comment]
你有理？有理发完消息退群。有理在这个我和说这种垃圾话？你冲动就把别人当你得奴隶可以随意说得？我只是以彼之道，还治其身你受不了了？大家都是俗人就不要在制高点去点评别人了。私人恩怨发到网上。怎么是想曝光什么？如果我是uview的工作人员是想让我没工作？劝你删贴吧有问题私聊不是有我qq吗。最后回复，别影响别人使用ui库。
