### ISSUE TITLE
vue3版本引入uView报错

### ISSUE THREAD

**Issue by tToyyLiang** [umicro/uView2.0#63]
![image](https://user-images.githubusercontent.com/41030139/143009738-256dd343-2b4c-4dda-a2ba-74a23c1da400.png)

![image](https://user-images.githubusercontent.com/41030139/143009875-f18b72af-c0f7-499b-b802-f69967169593.png)

**Comment by tToyyLiang** [comment]
![image](https://user-images.githubusercontent.com/41030139/143009980-a544aa92-a46f-4a1b-bd7a-548996caf507.png)

**Comment by tToyyLiang** [comment]
uniapp vue3 引入uView2.0.4，无法正常使用，浏览器出现上述报错

**Comment by ILfengzi** [comment]
应该是还不支持Vue3，插件市场显示平台兼容性不支持Vue3：https://ext.dcloud.net.cn/plugin?id=1593
