### ISSUE TITLE
navbar 如何去掉左侧返回 按钮？

### ISSUE THREAD

**Issue by sunshine0607** [umicro/uView2.0#640]
### 这个功能解决了什么问题？
navbar 不需要左侧返回就按钮，钉钉小程序如何实现

### 你期望的 API 是怎样的？
自定义标题栏，navbar 不需要左侧返回就按钮，微信小程序和钉钉小程序都需要隐藏

**Comment by yatoku** [comment]
用`left`这个插槽,内容设置为空的就可以
