### ISSUE TITLE
Calendar 日期计算错误

### ISSUE THREAD

**Issue by chuyun** [umicro/uView2.0#643]
### 版本
2.0.33

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/calendar.html)

### 重现步骤
最简接入，日期不符合预期
 <u-calendar
                :show="true"
              ></u-calendar>

![image](https://user-images.githubusercontent.com/19328403/176389182-bb992e4f-79c5-4eb5-8a95-11a0d2030914.png)

### 期望的结果是什么？
展示正常

### 实际的结果是什么？
日期异常

**Comment by yatoku** [comment]
我看示例项目没有问题啊 你自己改了什么样式吗？

**Comment by chuyun** [comment]
> 我看示例项目没有问题啊 你自己改了什么样式吗？

没有改，不过修改了全局单位为rpx

uni.$u.config.unit = 'rpx'

**Comment by yatoku** [comment]
> > 我看示例项目没有问题啊 你自己改了什么样式吗？
> 
> 没有改，不过修改了全局单位为rpx
> 
> uni.$u.config.unit = 'rpx'

这个是跟样式有关系的,把unit改成rpx以后 会有不少这种问题

**Comment by chuyun** [comment]
> 



> > > 我看示例项目没有问题啊 你自己改了什么样式吗？
> > 
> > 
> > 没有改，不过修改了全局单位为rpx
> > uni.$u.config.unit = 'rpx'
> 
> 这个是跟样式有关系的,把unit改成rpx以后 会有不少这种问题


是的，虽然支持修改，但是很多组件都依旧是 px

但是用px适配会存在一些问题
