### ISSUE TITLE
u-tabbar 的activeColor不生效

### ISSUE THREAD

**Issue by 694475668** [umicro/uView2.0#645]
### 版本
2.0.33

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/tabbar.html)

### 重现步骤
<u-tabbar zIndex="99999" :value="value" activeColor="red" inactiveColor="green"  @change="change" :fixed="true" :placeholder="true":safeAreaInsetBottom="true">
			<u-tabbar-item v-for="item in tabBarList" :text="item.text" :icon="item.icon" :name="item.name"></u-tabbar-item>
		</u-tabbar>

### 期望的结果是什么？
activeColor不管设置不设置都会生效

### 实际的结果是什么？
activeColor没有生效

**Comment by wujie-gis** [comment]
这个解决了吗

**Comment by 694475668** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wujie-gis** [comment]
> ### 版本
> 2.0.33
> 
> ### 转载链接
> [www.uviewui.com](https://www.uviewui.com/components/tabbar.html)
> 
> ### 重现步骤
> <u-tabbar zIndex="99999" :value="value" activeColor="red" inactiveColor="green" @change="change" :fixed="true" :placeholder="true":safeAreaInsetBottom="true">
> 
> ### 期望的结果是什么？
> activeColor不管设置不设置都会生效
> 
> ### 实际的结果是什么？
> activeColor没有生效
你把官方示例的uview-ui就可以

**Comment by yatoku** [comment]
可能你这个red的色值，在某个环境不支持

**Comment by yatoku** [comment]
![image](https://user-images.githubusercontent.com/35695074/189255479-2afb775b-2ba0-4d6c-9213-3805d483e16b.png)

**Comment by 694475668** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
