### ISSUE TITLE
u-popup>scroll-view>u-collapse>u-collapse-item>u-radio-group 显示popup时很慢

### ISSUE THREAD

**Issue by litdev** [umicro/uView2.0#649]
### 版本
2.0.33

### 转载链接
[http://www.uviewui.com/](http://www.uviewui.com)

### 重现步骤
u-popup
              scroll-view
                            u-collapse
                                           u-collapse-item
                                                           u-radio-group
这几级嵌套下来当设置show为true时显示的很慢，u-collapse-item越多越慢

### 期望的结果是什么？
速度加快

### 实际的结果是什么？
现在的显示速度得2s+，太影响体验了

**Comment by ChenLiuPng** [comment]
其实我在想 是不是设计不合理。 嵌套这么多层。。

**Comment by EthanZhuGit** [comment]
请问你解决了吗。我也在app上遇到这个问题，点击切换选中也特别慢。但同样的代码在微信小程序上就正常的

**Comment by litdev** [comment]
> 请问你解决了吗。我也在app上遇到这个问题，点击切换选中也特别慢。但同样的代码在微信小程序上就正常的

没有解决，目前u-collapse-item放的不多，所以这个问题不明显，你要是想解决，就别套这么多层了

**Comment by smartXJ** [comment]
u-popup > scroll-view > view 
我就三层 应该是数据多的问题显示很慢，我看了下原代码他们是用v-if来实现显示和隐藏功能的，用v-show会不会好点
