### ISSUE TITLE
【u-tabs】bug，在nvue和vue中表现不一致

### ISSUE THREAD

**Issue by JustGogoing** [umicro/uView2.0#65]
utabs组件,在nvue页面中引入正常,但是在vue页面中引入 H5端正常, app端(目前只测试了安卓) list长度直接溢出, ios端暂未测试
官网demo也有同样的问题,(但是demo是在nvue页面中使用 一切正常,创建一个vue页面就不行了)
![Screenshot_2021-11-23-17-01-35-886_HBuilder](https://user-images.githubusercontent.com/17309976/143155518-dd7c84e0-e616-4999-aea9-79e6f724ca77.png)

**Comment by JustGogoing** [comment]
手机是坚果pro2s 安卓8.1

**Comment by MarkGor** [comment]
u-tabs.vue
line:270
`
			&__scroll-view-wrapper {
				flex: 1;
				/* #ifndef APP-NVUE */
				width: 100%; //增加這個屬性
				overflow: auto hidden;
				/* #endif */
			}
`

**Comment by JustGogoing** [comment]
> u-tabs.vue line:270 `&__scroll-view-wrapper { flex: 1; /* #ifndef APP-NVUE */ width: 100%; //增加這個屬性 overflow: auto hidden; /* #endif */ }`

又失效了....
