### ISSUE TITLE
uView是否能够编译成支持非uniapp的前端项目的组件库？

### ISSUE THREAD

**Issue by Damocs0921** [umicro/uView2.0#650]
### 这个功能解决了什么问题？
希望在公司原有的用vue开发的h5项目中也使用uView组件库

### 你期望的 API 是怎样的？
既然uniapp能够把代码编译成各种小程序以及h5项目，
那么通过uniapp，uView能否被编译成一个普通的vue的web项目也能够直接import使用的组件库？谢谢

**Comment by yatoku** [comment]
不能
