### ISSUE TITLE
Picker 选择器什么时候支持地区级联选择功能啊

### ISSUE THREAD

**Issue by fendo8888** [umicro/uView2.0#657]
### 这个功能解决了什么问题？
uview2 Picker 选择器什么时候支持地区级联选择功能啊，很多场景都会用到这个，uview2 默认没有，这就有点尴尬。。

### 你期望的 API 是怎样的？
Picker 选择器什么时候支持地区级联选择功能

**Comment by AlwaysLoveme** [comment]
> 地区级联选择功能啊

省市区控件么？原生的picker就支持省市区选择，没必要再写一套了吧，
