### ISSUE TITLE
有支持Vue3的计划吗？

### ISSUE THREAD

**Issue by ILfengzi** [umicro/uView2.0#67]
请问近期有支持Vue3的计划吗？

**Comment by MarkGor** [comment]
nvue都还没完全稳定，
就跑来问vue支持计划，
而且项目说明已经有写，只有等uniapp对vue3完全兼容稳定后，才会开始vue3的开发....

**Comment by ILfengzi** [comment]
期待作者或者贡献者的解答

**Comment by MarkGor** [comment]
> 期待作者或者贡献者的解答
![image](https://user-images.githubusercontent.com/2922335/143374622-b6df3838-6250-49ae-ba64-21708da10e00.png)

**Comment by BeiQiaoT** [comment]
楼上说的没毛病，需要等dcloud的完全支持后，并且趋于稳定才会考虑vue3

**Comment by CNMathon** [comment]
> 楼上说的没毛病，需要等dcloud的完全支持后，并且趋于稳定才会考虑vue3

@BeiQiaoT 作者你好，那我们想确认下，目前有Vue3适配的相关排期吗？
