### ISSUE TITLE
APP-NVue Form表单报错[不是h5，是APP，随便填的链接，请不要随便关闭我的issue]

### ISSUE THREAD

**Issue by jackytse** [umicro/uView2.0#679]
### 版本
2.0.33

### 转载链接
[不是h5，是APP，随便填的链接，请不要随便关闭我的issue](https://ext.dcloud.net.cn/plugin?id=1593)

### 运行环境
HBuilderX版本： 3.4.18.20220630
操作系统： macOS 12.4
运行手机： 小米 11 LE   MIUI 13.0.2   Android 12

### 重现步骤
导入实例项目 https://ext.dcloud.net.cn/plugin?id=1593
运行到Android APP底座

进入 Form表单页面

### 期望的结果是什么？
正常显示Form表单页面

### 实际的结果是什么？
报错：
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught SyntaxError: Unexpected token ','

**Comment by littleboyck** [comment]
是的，我也出现了这个问题，很头疼

**Comment by littleboyck** [comment]
希望u-view官方各位大佬们可以，解决这个问题

**Comment by jackytse** [comment]
现在似乎没有这个问题了，难道是hbuilderx 的问题？
