### ISSUE TITLE
emmm，仓库更新的有点缓慢..o(╥﹏╥)o

### ISSUE THREAD

**Issue by wjw-gavin** [umicro/uView2.0#683]
### 这个功能解决了什么问题？
无

### 你期望的 API 是怎样的？
无

**Comment by ChenLiuPng** [comment]
主要是大家现在都在忙，愿意贡献自己力量的太少了

**Comment by wjw-gavin** [comment]
> 

嗯嗯，可以理解，主要是看很多pr没人合并...

**Comment by ChenLiuPng** [comment]
> > 
> 
> 嗯嗯，可以理解，主要是看很多人合并...

正常情况下是不能乱合的 得测试很多环境。

**Comment by wjw-gavin** [comment]
> > > 
> > 
> > 
> > 嗯嗯，可以理解，主要是看很多人合并...
> 
> 正常情况下是不能乱合的 得测试很多环境。

好的，期望越来越好哈
