### ISSUE TITLE
bug好多好多

### ISSUE THREAD

**Issue by zero-face** [umicro/uView2.0#69]
头像加载错误才显示默认头像，那么没有头像的时候，没有默认的头像占位。自定义导航栏还不如1版本好用，很多属性都不兼容，甚至直接冲突，大小单位不统一。我好难，我好难，我好难啊

**Comment by BeiQiaoT** [comment]
2.0本来就是不兼容1.0的，也不支持平滑升级，理解为两个不同的ui库

**Comment by MarkGor** [comment]
兼容nvue和vue本來就不簡單，
nvue實話說你自己嘗試開發一個項目，哪怕不用任何框架，都出現一大堆問題。
何況這個框架是對兩者做兼容。
就拿官方的uni-ui來對比，官方的大部分組件都直接不支持nvue，但uView2卻對兩者在做兼容，
而且剛發佈不到1個月，bug多是正常的，
如果僅僅是想拿來用，建議直接用1，沒必要用2
