### ISSUE TITLE
u-waterfall

### ISSUE THREAD

**Issue by weirenren** [umicro/uView2.0#696]
### 这个功能解决了什么问题？
nview 2.0 版本里缺少这个：Cannot find module '@/uni_modules/uview-ui/components/u-waterfall/u-waterfall.vue'

### 你期望的 API 是怎样的？
官方文档有介绍该功能，但是工程代码缺失

**Comment by yatoku** [comment]
uview2.0中是没有`u-waterfall`组件的，如果需要的话可以使用`nvue`自带的`waterfall`组件
