### ISSUE TITLE
2.0.2版uni.$u.http有问题

### ISSUE THREAD

**Issue by qzzm** [umicro/uView2.0#7]
uni.$u.http.post() 的 then 和 catch 是不是封装反了啊？？
 在 async中   await  uni.$u.http.post(url,data)  居然没办法往下运行，报错   Unhandled promise rejection

**Comment by YanxinNet** [comment]
经核实，此功能正常的，请您在浏览器控制台查看请求是否发出，配置是否正确，以及阅读相关文档使用方法。

**Comment by qzzm** [comment]
有请求发出返回数据，但是  连续两个post   就执行不到第二个 post
uni.$u.http.post(”这是一个有效的url地址“, {code: res.code}).then(res=>{
//then中没有响应，
}).catch((e)=>{
//响应是有返回的，但是是跳到这里，e.data 可以取得数据，只配置 config.baseURL 其它是默认配置
})
