### ISSUE TITLE
u-picker

### ISSUE THREAD

**Issue by stupidman001** [umicro/uView2.0#70]
这个组件点不了“确认”也点不了“取消”，坑死，现在删除不在用。。。。

**Comment by MarkGor** [comment]
無論點擊確認或取消，自己需要處理關閉事件；
即
`
<u-picker :show="show" @close="show=false" @confirm="show=false"></u-picker>
`

**Comment by BeiQiaoT** [comment]
本来就应该由开发者自行处理，到时候会在文档说明
