### ISSUE TITLE
u-search 设置 :clearabled="true" 清空输入框无效, 官方案例也不能清空

### ISSUE THREAD

**Issue by joe123345** [umicro/uView2.0#703]
### 版本
2.0.31

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/search.html)

### 重现步骤
...

### 期望的结果是什么？
输入框获取焦点, 用户输入内容 点击右边清除控件, 输入框内容清除

### 实际的结果是什么？
点击无效

**Comment by yatoku** [comment]
都可以的啊- -

**Comment by joe123345** [comment]
好的
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 上午9:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umicro/uView2.0] u-search 设置 :clearabled=&quot;true&quot; 清空输入框无效, 官方案例也不能清空 (Issue #703)





 
都可以的啊- -

**Comment by chitongyu** [comment]
+1，pc端不触发，不要把网页设置成手机模式

**Comment by joe123345** [comment]
好的，谢谢&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月29日(星期一) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umicro/uView2.0] u-search 设置 :clearabled=&quot;true&quot; 清空输入框无效, 官方案例也不能清空 (Issue #703)





 
+1，pc端不触发，不要把网页设置成手机模式
