### ISSUE TITLE
datetime-picker 组件没有监听 value的外部变化值

### ISSUE THREAD

**Issue by cander0815** [umicro/uView2.0#706]
### 版本
2.0.33

### 转载链接
[github.com](https://github.com/umicro/uView2.0/blob/master/uni_modules/uview-ui/components/u-datetime-picker/u-datetime-picker.vue#L77)

### 重现步骤
从代码中可得知，正常时间控制在编辑时，需要映射最新的值的

### 期望的结果是什么？
正常时间控制在编辑时，需要映射最新的值的

### 实际的结果是什么？
正常时间控制在编辑时，组件默认取自己内部的值进行展示

**Comment by yangxiongasin** [comment]
可以自行更改组件代码，将该组件代码的第90行最后添加this.value
