### ISSUE TITLE
组件已移除是否官方文档未更新

### ISSUE THREAD

**Issue by xya370** [umicro/uView2.0#728]
### 版本
2.0.33

### 转载链接
[http://localhost:8082/#/](http://localhost:8082/#/)

### 重现步骤
1. npm install uview-ui
2. 按照官方文档进行组件库配置
3. 在页面中引用u-card   u-tabs-swiper  组件 直接粘贴官网文档对应组件使用代码  

### 期望的结果是什么？
页面组件样式使用结果与官网文档展示一致

### 实际的结果是什么？
报错提示   WARNING: Module not found: Error: Can't resolve 'uview-ui/components/u-card/u-card.vue' 

Cannot find module 'uview-ui/components/u-card/u-card.vue'

---
uniapp程序使用npm install 下载组件库，在使用npm update 以及组件库卸载重装的情况下。 在使用过程中u-card 以及u-tabs-swiper  组件均报错无法找到，检查发现下载的组件中并无这两个组件，是否代码遗漏，或者组件已移除但官方在线文档未更新,  组件配置无问题 ， u-tabs组件可正常使用

**Comment by xya370** [comment]
> ### 版本
> 2.0.33
> 
> ### 转载链接
> http://localhost:8082/#/
> 
> ### 重现步骤
> 1. npm install uview-ui
> 2. 按照官方文档进行组件库配置
> 3. 在页面中引用u-card   u-tabs-swiper  组件 直接粘贴官网文档对应组件使用代码
> 
> ### 期望的结果是什么？
> 页面组件样式使用结果与官网文档展示一致
> 
> ### 实际的结果是什么？
> 报错提示 WARNING: Module not found: Error: Can't resolve 'uview-ui/components/u-card/u-card.vue'
> 
> Cannot find module 'uview-ui/components/u-card/u-card.vue'
> 
> uniapp程序使用npm install 下载组件库，在使用npm update 以及组件库卸载重装的情况下。 在使用过程中u-card 以及u-tabs-swiper 组件均报错无法找到，检查发现下载的组件中并无这两个组件，是否代码遗漏，或者组件已移除但官方在线文档未更新, 组件配置无问题 ， u-tabs组件可正常使用

**Comment by xya370** [comment]
好吧，是我找错了文档，建议在1.x版本的官方文档建一个可以跳转到2.x版本对应文档的入口，这样可以直接跳转版本文档

**Comment by yatoku** [comment]
![image](https://user-images.githubusercontent.com/35695074/189254111-2ccc5ccb-ad7e-45b6-9089-2c6a469189e5.png)
