### ISSUE TITLE
使用image、button组件中的@click事件点击后返回值为undefined，使用“data-”传值依然为undefined

### ISSUE THREAD

**Issue by yik7707** [umicro/uView2.0#734]
### 版本
2.0.33

### 转载链接
[localhost/](http://localhost:8081/#/pages/index/index)

图片组件
![QQ截图20220911173602](https://user-images.githubusercontent.com/74293458/189520907-5dd0f985-d0e5-4338-ad87-662e13c3cd87.png)

按钮组件
![QQ图片20220912171534](https://user-images.githubusercontent.com/74293458/189617379-73c00621-8e99-45ed-9781-8014fb0394ee.png)
![QQ图片20220912171538](https://user-images.githubusercontent.com/74293458/189617398-d3e48c1e-991f-4086-a80c-bf81d0e197ad.png)

### 重现步骤
使用image和button组件中的@click事件点击后返回值为undefined，使用“data-”传值依然为undefined，导致传值操作不便

### 期望的结果是什么？
修复并作出如下反馈效果，下面是原生button的@click事件
![QQ图片20220912171729](https://user-images.githubusercontent.com/74293458/189617824-16acdf9b-405f-4307-9233-f365c5b18539.png)
![QQ图片20220912171732](https://user-images.githubusercontent.com/74293458/189617844-3ef0a08e-af3b-4196-b6ce-5a5e3596819b.png)

### 实际的结果是什么？
并没有

**Comment by yatoku** [comment]
你可以`@click="add($event)"`

**Comment by JohnsonHwuang** [comment]
试了 `@click="add($event)"` 这个方式没有用 还是 undefined
