### ISSUE TITLE
Unknown custom element: <u--input>

### ISSUE THREAD

**Issue by heweicong** [umicro/uView2.0#736]
### 版本
2.0.33

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/setting.html)

### 重现步骤
main.ts已经引入uview 

import Vue from 'vue'
import App from './App.vue'
import { router, RouterMount } from './router'
import uView from 'uview-ui'
Vue.use(uView)
Vue.use(router)

Vue.config.productionTip = false

const app = new App()

// #ifdef H5
RouterMount(app, router, '#app')
// #endif

// #ifndef H5
app.$mount()
// #endif

然后在页面引用uview组件
        <u--input
            placeholder="请输入内容"
            border="surround"
            v-model="title"
        ></u--input>

### 期望的结果是什么？
期望显示元素

### 实际的结果是什么？
Unknown custom element: <u--input>

**Comment by yatoku** [comment]
请根据文档配置流程，查看自己是否已经配置完全
