### ISSUE TITLE
NoticeBar 滚动通知

### ISSUE THREAD

**Issue by wzlhappy** [umicro/uView2.0#739]
direction="column"的时候，text不是字符串数组，是[{title:'***'}]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/30285548/190371879-4dccc2a8-1759-482d-86b5-daa51f6835de.png">

**Comment by yatoku** [comment]
文档错误吗？

**Comment by wzlhappy** [comment]
应该是版本搞错了，项目u-column-notice里面循环text是{{item.title}} ，新拉的项目是{{item}}
