### ISSUE TITLE
action-sheet  设计不合理  closeOnClickAction必须和close搭配使用才有效

### ISSUE THREAD

**Issue by SunflowerGJ** [umicro/uView2.0#74]
<u-action-sheet :actions="systemASList" :show="showSystemAS" @select="e=>onASCallback(e,1)"
                :closeOnClickAction="true"  :closeOnClickOverlay="true" @close="showSystemAS = false"></u-action-sheet>

不管是原生还是其他各平台封装的actionSheet，取消按钮都是默认的，选中关闭这都是基本操作；你们封装的如果不设置参数，出来的根本就用不了的，为什么把它搞这么麻烦呢，不能简单点，默认样式不得尽量符合大众需求，少设置各种参数吗？

还有给了 closeOnClickAction参数，那理所应当我选中以后你直接给我关了就好了，结果还必须在外面写个close函数自己关掉；转了一圈都是我们写的代码自己关的，那你封装这个参数是干啥了，我要是想多写那句话，那我直接在@select函数里面把show=-false不就行了？ 这设计就不合理，而且文档也没说清楚，closeOnClickAction必须搭配close函数使用才有效，同理closeOnClickOverlay等

**Comment by SunflowerGJ** [comment]
既然让设置 closeOnClickAction了，那理所应当我选中以后你直接给我关了就好了，结果还必须在外面写个close函show=false关掉；转了一圈都是我们写的代码自己关的，那你封装这个参数是干啥了，我想自己关，那我直接在@select函数里面把show=-false不就行了？ 这设计就不合理，而且文档也没说清楚，必须写个close函数；

**Comment by MarkGor** [comment]
之前官方回復中有提到，參考了好像是react，
closeOnClickAction  為 true 時，會觸發close事件，
至於事件中需要如何去做，交給開發者自行處理。
我記得大概是這樣。
合不合理的見仁見智，只是文檔中如果 特別說明下 會更好；

**Comment by BeiQiaoT** [comment]
应由用户自行处理
