### ISSUE TITLE
SwipeAction问题集合，强烈建议修复

### ISSUE THREAD

**Issue by yik7707** [umicro/uView2.0#743]
### 版本
2.0.33

### 转载链接
[localhost/](http://localhost:8080/#/pages/tabbar/history/history)

以下问题运行编译到微信开发者工具发现的

问题1.swipe-action组件API文档/参数存在冲突
有时候需要传多个参数非常不便，name只能传一个参数，index可以传二个参数但是重叠了，我暂时使用的方法uilt的自定义循环找出选择的下标，希望尽快优化
![QQ截图20220918141749](https://user-images.githubusercontent.com/74293458/190888585-b37aab41-f378-418e-a1e0-f48000ddec74.png)
![QQ截图20220918142522](https://user-images.githubusercontent.com/74293458/190888835-e03f607e-6ab8-47a4-9424-08a4159db3f2.png)

问题2.使用hidden表现渲染形式，将SwipeAction作为两个组件在一个页面进行渲染，tab1和tab2，切换为tab2无法进行右侧滑动（下面体现部分代码）
![QQ截图20220918141416](https://user-images.githubusercontent.com/74293458/190888589-7f82fe59-3220-4204-b7c6-a0b67bbd0f77.png)
![QQ截图20220918151745](https://user-images.githubusercontent.com/74293458/190890478-b1826778-e6e6-4938-8085-59cc0b07512e.png)

问题3.autoClose参数默认为ture，未设置但是使用偶现失效，重启运行编译又没问题了（使用v-if渲染依然失效）
![QQ截图20220918141929](https://user-images.githubusercontent.com/74293458/190888629-12a9d72c-9806-4642-bb62-6111f4a7e525.png)
vue代码：
![QQ截图20220918142056](https://user-images.githubusercontent.com/74293458/190888696-30fe84e9-fc3b-4029-bd10-8348a8de1009.png)
组件代码：
![QQ截图20220918142209](https://user-images.githubusercontent.com/74293458/190888736-f49d8116-29ba-415c-8620-fd2a6f082216.png)

问题4.右侧按钮加上boderRadius，样式有圆角，宽高错乱如下图
![QQ截图20220924025616](https://user-images.githubusercontent.com/74293458/192038085-42aa848a-ab92-4475-a0d8-4794ae28e937.png)
![QQ截图20220924025749](https://user-images.githubusercontent.com/74293458/192038122-2f5b2cf7-11e6-441f-99c4-05cbcacae00c.png)

建议新增参数5.点击了item右侧按钮点击之后，自动回弹至1.原样，如下图所示
![QQ截图20220918145621](https://user-images.githubusercontent.com/74293458/190889742-98430bd5-e1e0-4c54-bcbb-515239c399ae.png)

### 重现步骤
问题1.打开该组件文档->SwipeActionItem Props中的参数 index（标识符，如果是v-for，可用index索引）->与SwipeActionItem Event中的click事件的参数index（右侧第几个按钮被点击），重叠参数且覆盖了SwipeActionItem Props中的参数 index，导致使用非常不便。（有时候需要传多个参数非常不便，name只能传一个参数，index可以传二个参数但是重叠了，我暂时使用的方法uilt的自定义循环找出选择的下标，希望尽快优化）

### 期望的结果是什么？
解决

### 实际的结果是什么？
并无

**Comment by huahai547** [comment]
SwipeAction  删除后无法复位  key和name都换成id也不管用
