### ISSUE TITLE
u-tabs的active-style和inactive-style的fontSize不一样导致切换tab时line位置错误

### ISSUE THREAD

**Issue by chaos-zhu** [umicro/uView2.0#744]
### 版本
2.0.33

### 重现步骤
```
  :active-style="{
    fontSize: '36rpx'
  }"
  :inactive-style="{
    fontSize: '28rpx'
  }"
```

### line位置错误
![image](https://user-images.githubusercontent.com/44160914/190945383-4b2eaca4-5093-4888-be22-db72f7c43f8f.png)
切换第二个tab时位置移动不正确
![image](https://user-images.githubusercontent.com/44160914/190945399-5ab3bc2d-a858-4ab3-b5ab-cb4e0c26fdc3.png)

### 期望的结果是什么？
正确显示位置

### 实际的结果是什么？
line位置错误

**Comment by webVictor** [comment]
出现了同样的问题，希望修复

**Comment by HellsingMatt** [comment]
不要用 fontSize，用 scale

**Comment by BIGMONK** [comment]
用了transform: 'scale(1.2)'还是时好时坏

**Comment by JadeSeven** [comment]
由于字体大小改变导致宽度变化，给固定宽度可以解决
