### ISSUE TITLE
DatetimePicker 数据和显示差异

### ISSUE THREAD

**Issue by eq1024** [umicro/uView2.0#747]
### 版本
2.0.33

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/datetimePicker.html)

### 重现步骤
DatetimePicker 中设置mode 为 date ,年月日模式,随便选择其中一项进行快速滚动,在滚动未完成时点击确定,此时前端依旧保持原状态,但是再次展开DatetimePicker则会显示滚动进行完后正确的数值.

### 期望的结果是什么？
前端显示和二次展开picker时的时间是同步的

### 实际的结果是什么？
picker内部时间会因为过早关闭picker而与预期不符

---
重现链接使用的是官方模板,存在相同问题

**Comment by yatoku** [comment]
uview中的`picker`相关的组件都是使用uniapp中的`picker-view`进行封装的，因为使用`picker-view`就会存在这种情况。目前有一个不成熟的解决方案你可以看看 https://github.com/umicro/uView2.0/pull/341
