### ISSUE TITLE
u-picker

### ISSUE THREAD

**Issue by Ynwaspectre** [umicro/uView2.0#75]
最后一个功能项 点击遮罩层取消  不生效

**Comment by MarkGor** [comment]
@close="showPicker=false"

2.0版本所有涉及 closeOnClickOverlay 都是觸發 close 事件，由開發者處理

**Comment by BeiQiaoT** [comment]
不提供，由用户自行处理，之后在文档加上

**Comment by shenxingchao** [comment]
最新版u-picker放在form外部才可以，放在form内部无法关闭picker

**Comment by helibin** [comment]
// 需延迟关闭, 原因: picker在form-item里,点击遮罩层会先触发遮罩层的close事件,后触发form-item的click事件

@close 事件延迟处理即可，setTimeout(() => xxx, 1)
