### ISSUE TITLE
route 路由跳转 type 不生效

### ISSUE THREAD

**Issue by AZmake** [umicro/uView2.0#771]
### 版本
2.0.34

### 转载链接
[www.uviewui.com/js/route.html](https://www.uviewui.com/js/route.html)

### 重现步骤
uni.$u.route({
          type: 'switchTab',
          url: '/pages/home/home',
          params: {
            name: 'lisa'
          }
        })

### 期望的结果是什么？
覆盖默认type

### 实际的结果是什么？
没有覆盖默认type

---
源码 route.js 56行

mergeConfig = uni.$u.deepMerge(options, this.config)

**Comment by zmb95** [comment]
官网已经更新了 但是uniapp  插件市场没有更新

**Comment by yatoku** [comment]
最新版本已修复

**Comment by snowchenlei** [comment]
10.29号更新到现在插件市场也没有新版本啊
