### ISSUE TITLE
使用uview List组件后，无法触发uniapp的下拉刷新事件

### ISSUE THREAD

**Issue by xfstu** [umicro/uView2.0#775]
### 版本
2.0.34

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/list.html)

### 重现步骤
```vue
<!-- test.vue -->
<template>
	<view>
		<u-list>
			<u-list-item></u-list-item>
		</u-list>
	</view>
</template>

<script>
	export default {
		data() {
			return {

			}
		},
		methods: {

		},
		onPullDownRefresh() {
			console.log(1)
		}
	}
</script>
```
```json
// pages.json
{
	"path": "pages/test/index",
	"style": {
		"navigationBarTitleText": "测试页",
		"enablePullDownRefresh": true
	}
}
```

### 期望的结果是什么？
按照示例代码后，应该出现加载图标，且触发onPullDownRefresh事件

### 实际的结果是什么？
无法触发下拉刷新（没有任何反应，包括界面和事件），删除u-list组件后正常刷新页面

---
环境是APP，Android11、红米K20pro 设计是想使用u-list组件，然后下拉刷新

**Comment by yatoku** [comment]
1.`u-list`在非`NVUE`的情况下,内部是使用`scroll-view`实现的。`scroll-view`中滚动是不会触发下拉事件的
2.不推荐使用`u-list`

**Comment by rookie-kl** [comment]
> 1.`u-list`在非`NVUE`的情况下，内部是使用`scroll-view`实现的。`scroll-view`中滚动是不会触发下拉事件的 2.不推荐使用`u-list`

那应该用什么  推荐一下
