### ISSUE TITLE
2.x版本 tabs无法滑动

### ISSUE THREAD

**Issue by 973299583** [umicro/uView2.0#78]
纯nvue项目，tabs无法滚动
查看uni官方文档建议的是 采用下面的方式获取节点信息
```js
const dom = uni.requireNativePlugin('dom');
const result = dom.getComponentRect(this.$refs.xxx, option => {
    console.log("节点信息", option)
})
```
但是我看咱们uview的代码里面好像并不是这样获取的 有尝试过自己改 无一例外都失败了

是不是这个原因导致的？还是说目前还不支持纯nvue项目？

**Comment by MarkGor** [comment]
nvue下正常
uview中也是通過dom來計算節點；
不過不確定和你的版本是不是一樣，我是拉取最新的。

**Comment by BeiQiaoT** [comment]
没复现，演示项目都正常
