### ISSUE TITLE
u-tooltip组件size设置不生效

### ISSUE THREAD

**Issue by ahhhhz** [umicro/uView2.0#780]
### 版本
2.0.33

### 转载链接
[https://www.uviewui.com/](https://www.uviewui.com)

### 重现步骤
<u-tooltip 
  text="abc"
  copy-text="abc"
  size="16px"
></u-tooltip>

### 期望的结果是什么？
size设置生效

### 实际的结果是什么？
size不生效

**Comment by better-tcy** [comment]
这个bug我已经提pr了 等作者同意就可以了

**Comment by Dragon-qx** [comment]
> 这个bug我已经提pr了 等作者同意就可以了

怎么解决的，我这里还是存在size不生效的问题

**Comment by ol0o0lo** [comment]
> 这个bug我已经提pr了 等作者同意就可以了

PR被关掉了，可能不符合规范，已再次提交
`fontSize: size + 'px'` 改成 `fontSize: $u.addUnit(size)`
