### ISSUE TITLE
有支持vue3的计划吗

### ISSUE THREAD

**Issue by wangchaochuan** [umicro/uView2.0#785]
### 这个功能解决了什么问题？
支持vue3

### 你期望的 API 是怎样的？
支持vue3

**Comment by xbmlz** [comment]
> ### 这个功能解决了什么问题？
> 支持vue3
> 
> ### 你期望的 API 是怎样的？
> 支持vue3

可以使用 vk-uview-ui，同时支持vue2.x和vue3.x， https://vkuviewdoc.fsq.pub/
或者现成的框架，很干净 
https://github.com/venable-dev/venable-uniapp
