### ISSUE TITLE
u-icon 在安卓机 显示 undefined 其他端OK的

### ISSUE THREAD

**Issue by cl-cc** [umicro/uView2.0#793]
### 版本
2.0.31

### 转载链接
[http://v1.uviewui.com/](http://v1.uviewui.com/)

### 重现步骤
升级了uview版本还是出现undefined 不知道咋回事

### 期望的结果是什么？
解决一下

### 实际的结果是什么？
解决一下

**Comment by aszx-fyh** [comment]
同样的问题

**Comment by aszx-fyh** [comment]
> 
可以 了，显示undefined是因为其他代码报错了
