### ISSUE TITLE
扫了微信小程序体验二维码，感觉组件点击有延迟，总感觉卡卡的。transition动画无效果

### ISSUE THREAD

**Issue by huanghaodong** [umicro/uView2.0#8]
扫了微信小程序体验二维码，感觉组件点击有延迟，总感觉卡卡的。transition动画无效果

**Comment by huanghaodong** [comment]
模态框淡入淡出也是没有效果的

**Comment by huanghaodong** [comment]
体验机型 iphonex

**Comment by YanxinNet** [comment]
iPhone手机运行太久了，会导致小程序和H5的css动画卡顿，这是普遍存在的问题，您可以尝试将微信关闭，再打开试试。

**Comment by huanghaodong** [comment]
> iPhone手机运行太久了，会导致小程序和H5的css动画卡顿，这是普遍存在的问题，您可以尝试将微信关闭，再打开试试。

收到，确实是这样。
