### ISSUE TITLE
代码注释中文乱码

### ISSUE THREAD

**Issue by varxzy** [umicro/uView2.0#800]
### 版本
2.0.34

### 转载链接
[github.com](https://github.com/umicro/uView2.0/blob/master/uni_modules/uview-ui/components/u-dropdown-item/u-dropdown-item.vue)

### 重现步骤
无

### 期望的结果是什么？
正常显示中文注释

### 实际的结果是什么？
中文注释乱码

**Comment by ChenLiuPng** [comment]
检查一下文件的编码格式？

**Comment by varxzy** [comment]
> 检查一下文件的编码格式？

但是随便打开其他文件就不是乱码，只有这个 u-dropdown 和 u-dropdown-item 这两个组件是

不乱码：
https://github.com/umicro/uView2.0/blob/master/uni_modules/uview-ui/components/u--input/u--input.vue

**Comment by yatoku** [comment]
> 

uview2是不支持`u-dropdown`组件的

**Comment by varxzy** [comment]
> > 
> 
> uview2是不支持`u-dropdown`组件的

搞笑呢，这是啥？
<img width="924" alt="image" src="https://github.com/umicro/uView2.0/assets/20296852/be505360-4421-4718-9dd2-628495032ffa">

**Comment by Ximeng0918** [comment]
> > > 
> > 
> > 
> > uview2是不支持`u-dropdown`组件的
> 
> 搞笑呢，这是啥？ <img alt="image" width="924" src="https://user-images.githubusercontent.com/20296852/255045715-be505360-4421-4718-9dd2-628495032ffa.png">

说白了就是2.0不支持这个组件，但是遗留的代码没有删除
