### ISSUE TITLE
在模拟器使用自定义基座+uview就无限重启

### ISSUE THREAD

**Issue by hengfei-xiao** [umicro/uView2.0#809]
### 版本
2.0.34

### 转载链接
[localhost/](http://localhost:8080/#/pages/login/login)

### 重现步骤
在hbuiderx中，点击运行到模拟器，使用自定义基座，进入任意含有uview组件的页面就会重启应用，删除uview组件，使用原生uniapp组件则正常。
如果在真机中则一切正常。

### 期望的结果是什么？
正常运行

### 实际的结果是什么？
无限重启

**Comment by yatoku** [comment]
请提供最小可重现案例

**Comment by htengweb** [comment]
同样问题，使用自定义基座，只要触发uview组件事件就会重启
