### ISSUE TITLE
兼容 vue 3.x 与相应的生态圈（vite、ts）

### ISSUE THREAD

**Issue by zhuyujie068** [umicro/uView2.0#813]
### 这个功能解决了什么问题？
解决对 vue 3.x 版本兼容性问题，融入其生态圈，享受其带来的优势与便利。

### 你期望的 API 是怎样的？
可以在 cli 创建的 uniapp 项目中使用其现版本的所有API。

**Comment by zhuyujie068** [comment]
可以了解社区解决方法：uview-plus   https://uiadmin.net/uview-plus/guide/demo.html

**Comment by yatoku** [comment]
uView2.0没有兼容vue 3.x及对应生态圈的计划，等3.0吧
