### ISSUE TITLE
QQ小程序样式及bug9个问题集合

### ISSUE THREAD

**Issue by yik7707** [umicro/uView2.0#819]
### 版本
2.0.34

### 转载链接
(https://ext.dcloud.net.cn/plugin?id=1593)

### 重现步骤

下载好Dcloud示例组件库zip，示例组件导入QQ小程序运行后：
示例组件中
1.tabbar出现不居中（居左且图片文字置顶）的情况（如果tabbar比较少3或2个就不好看），请适配样式
如下图所示
![QQ截图20221201221818](https://user-images.githubusercontent.com/74293458/205076039-624e86b9-09e6-46c2-a781-0991b602e811.png)

示例组件中
2.collapse折叠面板标题无论展开/不展开不显示的问题
![QQ截图20221201223122](https://user-images.githubusercontent.com/74293458/205079021-0a53e30d-216d-4272-9cd0-46e7d4e3a620.png)

示例组件中
3.grid宫格布局样式错乱
![QQ截图20221201221609](https://user-images.githubusercontent.com/74293458/205075534-06e94a1e-d18d-4cd9-9d35-688926897cde.png)

示例组件中
4.吸顶sticky不起作用
![QQ截图20221201221528](https://user-images.githubusercontent.com/74293458/205075385-157cb529-f93d-4298-809e-2b9962d2994f.png)

示例组件中
5.Divider分割线样式不居中
![QQ截图20221201221438](https://user-images.githubusercontent.com/74293458/205075160-09b976ce-c13d-4422-a9d0-9b61205d6d53.png)

示例组件中
6.Tabs标签点击后频繁提示如下图错误
![QQ截图20221201222032](https://user-images.githubusercontent.com/74293458/205076591-d5547959-2ff2-41bc-96f3-54913d0848b6.png)

示例组件中
7.lndexList索引列表拖动时失效
![QQ截图20221201222433](https://user-images.githubusercontent.com/74293458/205077535-40ca0838-40d8-4e6b-9f7c-9bb0196343cf.png)

8.Steps步骤条不占整行，请适配样式
![QQ截图20221201222651](https://user-images.githubusercontent.com/74293458/205078526-5974aa4e-c568-408b-8664-28679a3ac553.png)

示例组件中
9.form表单直接校验通过，正则表达式存在bug（微信小程序则正常）
![QQ截图20221201221719](https://user-images.githubusercontent.com/74293458/205075778-024ae365-e2eb-4583-9487-82da1974de81.png)

### 期望的结果是什么？
请尽快适配样式并修复以上bug

### 实际的结果是什么？
未解决

**Comment by Smartiboy** [comment]
以上问题均可通过调整样式自行解决

**Comment by yik7707** [comment]
@Smartiboy 这上面不仅有样式问题还有bug问题

**Comment by wzhsh90** [comment]
感觉uview 在qq 平台都没有做测试，骗人的。问题多得很。

主要原因是qq 平台virtualHost 不支持。

qq 小程序开发人员不晓得是一群什么人，几年了还是老样子 , 很旧以前的bug 一样存在。
