### ISSUE TITLE
u-datetime-picker中描述错误

### ISSUE THREAD

**Issue by ArealRJ** [umicro/uView2.0#828]
### 版本
2.0.34

### 转载链接
[www.uviewui.com](https://www.uviewui.com/components/datetimePicker.html)

### 重现步骤
限制最大值与最小值那里的描述应该是minDate和maxDate，官方文档写的minDate与maxData。

### 期望的结果是什么？
参数minDate和maxDate可以设置最大值和最小值（传入时间戳）。

### 实际的结果是什么？
参数minDate和maxData可以设置最大值和最小值（传入时间戳）。

**Comment by yatoku** [comment]
文档和代码中都是`maxDate`啊，你这个`maxData`是怎么来的？

**Comment by ArealRJ** [comment]
我这里看到的确实是maxData




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umicro/uView2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月16日(星期五) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umicro/uView2.0] u-datetime-picker中描述错误 (Issue #828)





 
文档和代码中都是maxDate啊，你这个maxData是怎么来的？

**Comment by yatoku** [comment]
![image](https://user-images.githubusercontent.com/35695074/208007493-3660d45b-34fc-4515-9ac2-7e7d33334488.png)
![image](https://user-images.githubusercontent.com/35695074/208007573-63a56165-3cbf-46f7-a0ae-0daf1a5269ab.png)
你在那里看到的，能发一下吗

**Comment by ArealRJ** [comment]
https://www.uviewui.com/components/datetimePicker.html


是上面的示例里




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umicro/uView2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月16日(星期五) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umicro/uView2.0] u-datetime-picker中描述错误 (Issue #828)





 

 
 你在那里看到的，能发一下吗

**Comment by yatoku** [comment]
你说这个吗
![image](https://user-images.githubusercontent.com/35695074/208020724-291a5e59-7373-4f4b-9c1a-eaf961f70df4.png)

**Comment by yatoku** [comment]
改了
