### ISSUE TITLE
u-transition 这里阻止了touchmove冒泡导致 H5 组件不能正常作为触点滚动

### ISSUE THREAD

**Issue by 6xiaowu9** [umicro/uView2.0#83]
u-transition 这里阻止了 touchmove 冒泡导致 H5 组件不能正常作为触点滚动，不知道这里这么做的原因是什么？

我这边在使用u-image的时候遇到了这个问题，当触点在image上时，无法滑动页面

**Comment by BeiQiaoT** [comment]
拉取新版本，已处理
