### ISSUE TITLE
支付宝小程序的form组件没有validate等函数,微信小程序正常

### ISSUE THREAD

**Issue by mjgzy** [umicro/uView2.0#835]
### 版本
2.0.34

### 转载链接
[http://127.0.0.1:7890/](http://127.0.0.1:7890)

### 重现步骤
一个简单的表单页面,在提交函数中调用validate函数,微信小程序正常,支付宝小程序提示that.$refs.form1.validate is not a function

### 期望的结果是什么？
验证函数正常验证

### 实际的结果是什么？
提示验证函数不存在

**Comment by mjgzy** [comment]
微信小程序:
![image](https://user-images.githubusercontent.com/55934340/209515472-a5cf7472-b778-4902-8aa8-eb35c0006cd0.png)
支付宝小程序：
![image](https://user-images.githubusercontent.com/55934340/209515599-cebecedd-2c56-4d24-b8af-4563a542cdf0.png)

**Comment by mjgzy** [comment]
![image](https://user-images.githubusercontent.com/55934340/209515902-e4d229a0-14b9-4676-b45c-335b52eeee95.png)

**Comment by mjgzy** [comment]
已证实是没有开启component2配置

**Comment by arShen6** [comment]
> 已证实是没有开启component2配置

请问解决了吗？为什么我开启conponent2没有啊？只有string能用，其他类型就不行，反正是有点bug
