### ISSUE TITLE
List 列表组件在小程序中异常滚动问题。

### ISSUE THREAD

**Issue by 1529829142** [umicro/uView2.0#853]
### 版本
2.0.34

### 转载链接
[localhost](https://localhost/components/list.html)

### 重现步骤
直接copy例子代码，会发现运行到小程序上滚动到底部加载下一页时会出现抖动问题。

### 期望的结果是什么？
解决问题

### 实际的结果是什么？
解决问题

---
添加属性 preLoadScreen="page * 4" 解决

**Comment by yatoku** [comment]
#149
