### ISSUE TITLE
u-calendar无法选择之前的时间，选择的时间范围只可以是今天之后的

### ISSUE THREAD

**Issue by youlongxifeng** [umicro/uView2.0#875]
### 版本
2.0.34

### 转载链接
[10.210.63.177](http://10.210.63.177:8082/pages/componentsC/calendar/calendar)

### 重现步骤
http://10.210.63.177:8082/pages/componentsC/calendar/calendar 直接选择日期，只可以选择今天之后的，不可以选择今天之前的日期。

### 期望的结果是什么？
可以选择之前的时间

### 实际的结果是什么？
不可以选择之前的时间

**Comment by mangdehuang** [comment]
<u-calendar :show="true" minDate='2023-2-01' defaultDate='2023-03-08'></u-calendar>

**Comment by mangdehuang** [comment]
<u-calendar :show="true" minDate='2023-2-01' defaultDate='2023-03-08'></u-calendar>

**Comment by yatoku** [comment]
可以设置`minDate`，它默认是今天。如果时间跨度较大的话需要设置`monthNum `默认是三个月
