### ISSUE TITLE
u-datetime-picker mode = 'time' 在选择改变时间时，控制台报错

### ISSUE THREAD

**Issue by TEABOY-WEB** [umicro/uView2.0#88]
![image](https://user-images.githubusercontent.com/69789908/143676899-5a8bfc24-ea87-4d0b-998a-879d98a87c25.png)

**Comment by TEABOY-WEB** [comment]
这个地方少解构了个value
![image](https://user-images.githubusercontent.com/69789908/143677534-cc049933-89b7-4697-a0b6-f44da9645e4b.png)

**Comment by BeiQiaoT** [comment]
没复现

**Comment by TEABOY-WEB** [comment]
录了屏，您可以在确认一下，我这边真机调试时，时间一直是初始的默认时间。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umicro/uView2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月28日(星期天) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umicro/uView2.0] u-datetime-picker mode = 'time' 在选择改变时间时，控制台报错 (Issue #88)





 
Closed #88.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BeiQiaoT** [comment]
复现了，我排查一下
