### ISSUE TITLE
在1.x版本中日历组件能切换年份和月份，反而到了2.x版本，为啥把这个功能阉割了，哪有日历不能切换月份和年份的

### ISSUE THREAD

**Issue by baomihuayu** [umicro/uView2.0#882]
### 版本
2.0.34

### 转载链接
[v1.uviewui.com](http://v1.uviewui.com/components/calendar.html)

### 重现步骤
2.x:https://www.uviewui.com/components/calendar.html
1.x:http://v1.uviewui.com/components/calendar.html

### 期望的结果是什么？
日历组件添加年份切换和月份切换

### 实际的结果是什么？
无年份切换和月份切换

**Comment by xiangnanscu** [comment]
确实是哈，感觉是不是放弃治疗了。KPI项目？

**Comment by yatoku** [comment]
因为2.x和1.x的实现方式不一样

**Comment by baomihuayu** [comment]
> 因为2.x和1.x的实现方式不一样
哈？实现不一样就阉割功能？哪个日历是这样子

**Comment by mythbobo** [comment]
刚升级到2.0,就碰到各种头痛问题。日历默认不能选择以前的时间，不能切换月份和年份，input把select类型去掉了。以前很方便的一些功能全都没了。不知道是怎么想的
