### ISSUE TITLE
小程序报错e.requireNativePlugin is not a function

### ISSUE THREAD

**Issue by blaze87** [umicro/uView2.0#9]
小程序会报错： 页面【node-modules/uview-ui/components/u-transition/u-transition]错误，注释掉：const animation = uni.requireNativePlugin('animation')就ok

**Comment by tttao7** [comment]
```
// #ifdef APP-NVUE
// 引入nvue(weex)的animation动画模块，文档见：
// https://weex.apache.org/zh/docs/modules/animation.html#transition
const animation = uni.requireNativePlugin('animation')
const getStyle = (name) => animationMap[name]
// #endif
```

小程序中是不会编译此行的，请检查代码。

**Comment by cxy-coder** [comment]
[我也需要了这个问题，在HBuilderX中编译是正常的也打开了微信开发者工具了，但是微信开发者工具中报错了
![image](https://user-images.githubusercontent.com/51732786/142372719-2c7016e3-7a34-4e4b-aed6-f6278871cafb.png)

**Comment by coderchang0105** [comment]
我也遇到了这个问题

**Comment by yangerlang** [comment]
同样遇到了
![image](https://user-images.githubusercontent.com/16792231/143997894-a99a0091-e14c-45ae-84af-6db07b942876.png)
![image](https://user-images.githubusercontent.com/16792231/143997926-18e58da6-ff3d-4958-80f8-f857762ec2cb.png)
