### ISSUE TITLE
表单验证的pattern不起作用

### ISSUE THREAD

**Issue by weijiehuang** [umicro/uView2.0#91]
phone: [{
    type: 'string',
    required: true,
    message: '请输入手机号',
    trigger: ['blur', 'change']
  }, {
    pattern: /^1[2-9]\d{9}$/g,
    message: '请输入有效的手机号',
    trigger: ['blur', 'change']
  }],

**Comment by wzohxia** [comment]
validator 也不起作用

**Comment by pandaGames** [comment]
> validator 也不起作用

+ 1

**Comment by BeiQiaoT** [comment]
已调整

**Comment by wzohxia** [comment]
> 已调整

如果是刚发布的版本 并没有调整，是否是下个版本？？

**Comment by mastercbhw** [comment]
> 已调整

版本2.0.29中，uni写微信小程序使用时候，validator不起作用

**Comment by mastercbhw** [comment]
> > 已调整
> 
> 版本2.0.29中，uni写微信小程序使用时候，validator不起作用

使用uni写的微信小程序，需要setRules了才可以生效。是我没有看仔细文档，sorry
```
  onReady() {
    this.$refs.uForm.setRules(this.rules)
  },
```
