### ISSUE TITLE
啥玩意，u-toast文档写着传递title，源码写着传message，干啥呢，希望你们修正一下

### ISSUE THREAD

**Issue by 1596944197** [umicro/uView2.0#911]
### 版本
2.0.36

### 转载链接
[http://127.0.0.1/](http://127.0.0.1)

### 重现步骤
直接走官网demo，不行，得把title改为message.

### 期望的结果是什么？
1

### 实际的结果是什么？
2

---
3

**Comment by yatoku** [comment]
[v](https://www.uviewui.com/components/toast.html#api)
