### ISSUE TITLE
【Bug】u-datetime-picker组件，传入的v-model不支持动态修改

### ISSUE THREAD

**Issue by xintianyou** [umicro/uView2.0#914]
### 转载链接
[http://localhost:9000/#/](http://localhost:9000/#/)

### 重现步骤
使用[官方文档DatetimePicker](https://www.uviewui.com/components/datetimePicker.html)上的代码示例稍作修改
```
<template>
      <view>
           <u-datetime-picker
                :show="show"
                v-model="value1"
                mode="date"
                @cancel="show = false"
           ></u-datetime-picker>
	   <u-button @click="show = true">打开</u-button>
    
	   <u-button @click="changeDefault">修改默认时间</u-button>
       </view>
</template>

<script>
	export default {
		data() {
			return {
				show: false,
                                 value1: Number(new Date()),
			}
		},
                 methods: {
                         changeDefault() {
                                 this.value1 = Number(new Date('2020-11-25'))
                         }
                 }
	}
</script>
```
先点击打开按钮，可以看到默认选中的是当前的日期，这没错，正是我期望的。
增加了一个修改默认值的操作，将默认值改为其他日期（例如：2020-11-25）的时间戳。

### 期望的结果是什么？
修改默认值后，再次打开picker，默认选中修改后的日期/时间

### 实际的结果是什么？
再次点击打开按钮，发现默认选中的还是当前日期时间。
将mode改为time或者datetime，结果也是一样。

[![i9EyNX.md.png](https://i.328888.xyz/2023/04/27/i9EyNX.md.png)](https://imgloc.com/i/i9EyNX)

**Comment by xintianyou** [comment]
[![i9EyNX.md.png](https://i.328888.xyz/2023/04/27/i9EyNX.md.png)](https://imgloc.com/i/i9EyNX)

**Comment by Luxuff** [comment]
u-datetime-picker.vue 里有个 show(newValue, oldValue) 函数，原逻辑是 this.updateColumnValue(this.innerValue)，但 this.innerValue 只会在初始化组件时更新一遍，把它改成 this.updateColumnValue(this.correctValue(this.value)) 就可以每次打开都更新了。

**Comment by rookie-kl** [comment]
> u-datetime-picker.vue 里有个 show(newValue, oldValue) 函数，原逻辑是 this.updateColumnValue(this.innerValue)，但 this.innerValue 只会在初始化组件时更新一遍，把它改成 this.updateColumnValue(this.correctValue(this.value)) 就可以每次打开都更新了。

哪还有什么办法嘛，只能改源码了嘛
