### ISSUE TITLE
u--image  "Property or method "borderRadius" is not defined"

### ISSUE THREAD

**Issue by wjq152** [umicro/uView2.0#93]
### 版本
2.0.6

### 转载链接
[github.com](https://github.com/umicro/uView/blob/master/uview-ui/components/u-image/u-image.vue#L31;https://github.com/umicro/uView/blob/master/uview-ui/components/u-image/u-image.vue#L188)

### 重现步骤
u--image 填写 radius 时
1.x 为 borderRadius 2.x 应为radius ，computed 内 borderRadius、与  class 为 u-image__error区域  未修改为radius

### 期望的结果是什么？
修复此问题至master

### 实际的结果是什么？
修复此问题至master

**Comment by orangepro11** [comment]
已修复
