### ISSUE TITLE
为什么插件市场看到更新记录和时间，GitHub 仓库看不到？

### ISSUE THREAD

**Issue by dong-lufei** [umicro/uView2.0#933]
### 这个功能解决了什么问题？
更新记录

### 你期望的 API 是怎样的？
https://ext.dcloud.net.cn/plugin?id=8744#rating
更新记录

我在 https://github.com/ijry/uview-plus 仓库提的 Issues 咋跑到这来了。是一家？

我要用uVew的支持vue3的组件

**Comment by yatoku** [comment]
不是同一家的
