### ISSUE TITLE
video组件会覆盖自定义导航，穿透到自定义导航上面

### ISSUE THREAD

**Issue by shangchuan123** [umicro/uView2.0#937]
### 版本
2.0.36

### 转载链接
[http://sd.sbss.com/u-navbar](http://sd.sbss.com/u-navbar)

### 重现步骤
video组件会覆盖自定义导航，穿透到自定义导航上面

### 期望的结果是什么？
video元素不要穿透到自定义导航组件u-navbar上面

### 实际的结果是什么？
video元素穿透到自定义导航组件u-navbar上面

**Comment by yatoku** [comment]
`video`是原生组件，如果不是`nvue`的话层级是最高的，如果有类似需求只能使用`nvue`
