### ISSUE TITLE
u-picker在支付宝小程序样式错误

### ISSUE THREAD

**Issue by kungege** [umicro/uView2.0#953]
### 版本
2.0.36

### 转载链接
[http://192.168.0.114/](http://192.168.0.114/)

### 重现步骤
<img width="988" alt="image" src="https://github.com/umicro/uView2.0/assets/16132584/e01f618c-f378-4633-8811-94803438d210">

### 期望的结果是什么？
正常显示

### 实际的结果是什么？
<img width="402" alt="image" src="https://github.com/umicro/uView2.0/assets/16132584/ad96953a-bfa8-4bd7-8f74-de9c41781179">

**Comment by chenqq2436** [comment]
我也遇到了同样的问题，请问你解决了吗？

**Comment by kungege** [comment]
> 我也遇到了同样的问题，请问你解决了吗？

@chenqq2436 看我的pr
