### ISSUE TITLE
u-datetime-picker在支付宝小程序，默认组件样式丢失错了

### ISSUE THREAD

**Issue by hasbug** [umicro/uView2.0#954]
### 版本
2.0.36

### 转载链接
[i.chuangetu.com](https://i.chuangetu.com/image/2023/06/15/EEKq0.png)

### 重现步骤
页面中使用u-datetime-picker组件用来选择年和月，但在支付宝小程序中发现，样式丢失，全部成了一行。

### 期望的结果是什么？
能够正常显示一行一个选项

### 实际的结果是什么？
[![EEKq0.png](https://i.chuangetu.com/image/2023/06/15/EEKq0.png)](http://chuangetu.com/image/EEKq0)

---
从2.0.31至2.0.36都存在的问题。

**Comment by arShen6** [comment]
@BeiQiaoT  请问一下，你fix这个bug，我是npm安装的，我如果要用的话，只能下载下来用吗？
