### ISSUE TITLE
form验证的正则跟validator还是不起效果的，issue被关

### ISSUE THREAD

**Issue by wzohxia** [umicro/uView2.0#99]
### 版本
2.0.7

### 转载链接
[github.com](https://github.com/umicro/uView2.0/issues/91)

### 重现步骤
接被关闭的issue   
https://github.com/umicro/uView2.0/issues/91

### 期望的结果是什么？
验证起效

### 实际的结果是什么？
验证不起效

**Comment by pandaGames** [comment]
u--form的validate都吞掉了callback，然后u-form的validate也没调用callback🔮🔮🔮

**Comment by Haiwar** [comment]
uView2.0不能在支付宝小程序下运行...
![image](https://user-images.githubusercontent.com/35055270/144021936-8925a870-52cc-42fa-803d-32d77a899f57.png)

**Comment by BeiQiaoT** [comment]
你看一下官网的form说明，今天更新的

**Comment by LiangFuzhi** [comment]
在小程序，根本就没有执行到validator这个函数

**Comment by arShen6** [comment]
> 在小程序，根本就没有执行到validator这个函数

请问你解决了吗？
