### ISSUE TITLE
search设置disabled为true时，点击输入框，onclick事件无效

### ISSUE THREAD

**Issue by zzw0420** [umicro/uView2.0#995]
### 版本
2.0.36

### 转载链接
[localhost/](http://localhost:8080/#/pages/quotations/quotations)

### 重现步骤
search 设置disabled后，直接点击search控件，事件接收不到

### 期望的结果是什么？
事件方法有调用

### 实际的结果是什么？
事件方法无调用

---
演示中在h5环境中也是没用的

**Comment by yatoku** [comment]
你可以使用`@click.native`来进行监听
